name = "simply-enak-website"
compatibility_date = "2024-01-01"

[env.staging]
name = "simply-enak-staging"

[[env.staging.kv_namespaces]]
binding = "SESSION"
id = "your-kv-namespace-id"

[env.production]
name = "simply-enak-production"

[[env.production.kv_namespaces]]
binding = "SESSION"
id = "your-kv-namespace-id"