name = "simply-enak-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.staging]
name = "simply-enak-staging"
pages_build_output_dir = "dist"

[[env.staging.kv_namespaces]]
binding = "SESSION"
id = "your-kv-namespace-id"

[env.production]
name = "simply-enak-production"
pages_build_output_dir = "dist"

[[env.production.kv_namespaces]]
binding = "SESSION"
id = "your-kv-namespace-id"