name = "revamp"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production.vars]
PUBLIC_PAYLOAD_URL = "https://cms.system.simplyenak.com"

[env.preview.vars]
PUBLIC_PAYLOAD_URL = "https://cms.system.simplyenak.com"