/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tours: Tour;
    stories: Story;
    testimonials: Testimonial;
    faqs: Faq;
    media_coverage: MediaCoverage;
    dietary_options: DietaryOption;
    food_items: FoodItem;
    vendors: Vendor;
    dietary_landing_pages: DietaryLandingPage;
    specialty_landing_pages: SpecialtyLandingPage;
    travel_type_landing_pages: TravelTypeLandingPage;
    location_landing_pages: LocationLandingPage;
    about_page: AboutPage;
    contact_page: ContactPage;
    thank_you_pages: ThankYouPage;
    home_page: HomePage;
    legal_pages: LegalPage;
    menus: Menu;
    travel_types: TravelType;
    specialty_experiences: SpecialtyExperience;
    locations: Location;
    translations: Translation;
    site_settings: SiteSetting;
    exports: Export;
    imports: Import;
    redirects: Redirect;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media_coverage: MediaCoverageSelect<false> | MediaCoverageSelect<true>;
    dietary_options: DietaryOptionsSelect<false> | DietaryOptionsSelect<true>;
    food_items: FoodItemsSelect<false> | FoodItemsSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    dietary_landing_pages: DietaryLandingPagesSelect<false> | DietaryLandingPagesSelect<true>;
    specialty_landing_pages: SpecialtyLandingPagesSelect<false> | SpecialtyLandingPagesSelect<true>;
    travel_type_landing_pages: TravelTypeLandingPagesSelect<false> | TravelTypeLandingPagesSelect<true>;
    location_landing_pages: LocationLandingPagesSelect<false> | LocationLandingPagesSelect<true>;
    about_page: AboutPageSelect<false> | AboutPageSelect<true>;
    contact_page: ContactPageSelect<false> | ContactPageSelect<true>;
    thank_you_pages: ThankYouPagesSelect<false> | ThankYouPagesSelect<true>;
    home_page: HomePageSelect<false> | HomePageSelect<true>;
    legal_pages: LegalPagesSelect<false> | LegalPagesSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    travel_types: TravelTypesSelect<false> | TravelTypesSelect<true>;
    specialty_experiences: SpecialtyExperiencesSelect<false> | SpecialtyExperiencesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    translations: TranslationsSelect<false> | TranslationsSelect<true>;
    site_settings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * 👤 User accounts and authentication
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * User role determines what they can access and edit
   */
  role: 'admin' | 'editor' | 'translator' | 'reviewer';
  /**
   * Full name for display
   */
  fullName?: string | null;
  /**
   * Department or team (e.g., Marketing, Translations)
   */
  department?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * 📸 Image and media library for all content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility
   */
  alt?: string | null;
  /**
   * Optional caption
   */
  caption?: string | null;
  /**
   * Where is this image used? (e.g., tours, stories, etc.)
   */
  usage?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * 🚌 Tour offerings and packages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  /**
   * The official tour name (e.g., "Flavours of Malaysia")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "flavours-of-malaysia")
   */
  slug: string;
  /**
   * Short, catchy phrase (e.g., "Off the Beaten Track")
   */
  tagline?: string | null;
  /**
   * Brief overview for listing pages (2-3 sentences)
   */
  shortDescription?: string | null;
  /**
   * Complete tour description for detail pages
   */
  fullDescription?: string | null;
  /**
   * Price in MYR
   */
  price?: number | null;
  /**
   * Currency code
   */
  currency?: string | null;
  /**
   * Human-readable (e.g., "4 hours")
   */
  duration?: string | null;
  /**
   * Duration in minutes for calculations
   */
  durationMinutes?: number | null;
  /**
   * City/area (e.g., "Kuala Lumpur", "Penang")
   */
  location?: string | null;
  /**
   * Where participants should gather
   */
  meetingPoint?: string | null;
  /**
   * Maximum group size
   */
  maxParticipants?: number | null;
  /**
   * Minimum group size (default: 2)
   */
  minParticipants?: number | null;
  /**
   * Select dietary options available on this tour (managed in Dietary Options)
   */
  dietaryOptions?: (number | DietaryOption)[] | null;
  /**
   * Select travel types this tour suits (managed in Travel Type Landing Pages)
   */
  travelTypes?: (number | TravelTypeLandingPage)[] | null;
  /**
   * Select specialty experiences featured (managed in Specialty Landing Pages)
   */
  specialtyExperiences?: (number | SpecialtyLandingPage)[] | null;
  /**
   * Select food and drink items featured on this tour
   */
  foodItems?: (number | FoodItem)[] | null;
  /**
   * Can this tour be customized/tailored?
   */
  tailoredAvailable?: boolean | null;
  /**
   * Notes about customization options
   */
  tailoredNotes?: string | null;
  /**
   * Main tour image URL
   */
  heroImage?: string | null;
  /**
   * Additional tour photos
   */
  galleryImages?:
    | {
        image: string;
        id?: string | null;
      }[]
    | null;
  /**
   * What is included in the tour price
   */
  whatsIncluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * What is NOT included in the tour price
   */
  whatsExcluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tour highlights and key features
   */
  highlights?:
    | {
        highlight: string;
        id?: string | null;
      }[]
    | null;
  /**
   * External booking link (if applicable)
   */
  bookingUrl?: string | null;
  /**
   * Bookings are confirmed immediately
   */
  instantConfirmation?: boolean | null;
  /**
   * Auto-publish at this date/time (leave empty for immediate)
   */
  scheduledPublish?: string | null;
  /**
   * Show on homepage and featured tours section
   */
  featured?: boolean | null;
  /**
   * Mark as popular/bestseller
   */
  popular?: boolean | null;
  /**
   * Mark as new tour
   */
  new?: boolean | null;
  /**
   * When tour was published
   */
  publishedAt?: string | null;
  /**
   * Draft = hidden, Published = visible on website
   */
  status?: ('draft' | 'published') | null;
  /**
   * Workflow approval status
   */
  workflowStatus?: ('draft' | 'in_review' | 'approved' | 'published') | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 🥗 Dietary options reference (Vegetarian, Halal, Vegan, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dietary_options".
 */
export interface DietaryOption {
  id: number;
  /**
   * Dietary option name (e.g., "Vegetarian", "Halal")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "vegetarian")
   */
  slug: string;
  /**
   * Icon name or emoji (e.g., "🌱", "leaf")
   */
  icon?: string | null;
  /**
   * Color code for UI display (e.g., "#22c55e")
   */
  color?: string | null;
  /**
   * Brief description of this dietary option
   */
  description?: string | null;
  /**
   * Draft = hidden, Published = available for selection
   */
  status?: ('draft' | 'published') | null;
  /**
   * Auto-publish at this date/time
   */
  scheduledPublish?: string | null;
  /**
   * When this dietary option was published
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 🧳 Travel type landing pages (Family, Couples, Solo, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel_type_landing_pages".
 */
export interface TravelTypeLandingPage {
  id: number;
  travel_type_name: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  icon?: string | null;
  color?: string | null;
  /**
   * Hero section with title, subtitle, description, and image
   */
  heroSection?:
    | {
        title?: string | null;
        subtitle?: string | null;
        description?: string | null;
        image?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroBlock';
      }[]
    | null;
  /**
   * Why this travel type is perfect for our tours
   */
  whyPerfectSection?:
    | {
        title?: string | null;
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentBlock';
      }[]
    | null;
  /**
   * What to expect on tours for this travel type
   */
  expectSection?:
    | {
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentBlock';
      }[]
    | null;
  /**
   * Tips for this travel type
   */
  tipsSection?:
    | {
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'tipsBlock';
      }[]
    | null;
  /**
   * Which tours suit this travel type
   */
  suitableToursSection?:
    | {
        /**
         * Tour slugs that suit this travel type
         */
        tours?:
          | {
              slug: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'tourListBlock';
      }[]
    | null;
  /**
   * Key features of this travel type
   */
  keyFeaturesSection?:
    | {
        /**
         * Key features
         */
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featuresBlock';
      }[]
    | null;
  meta_title?: string | null;
  meta_description?: string | null;
  published_at?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * ⭐ Specialty landing pages (Street Food, Market Tours, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialty_landing_pages".
 */
export interface SpecialtyLandingPage {
  id: number;
  specialty_name: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  icon?: string | null;
  color?: string | null;
  /**
   * Hero section with title, subtitle, description, and image
   */
  heroSection?:
    | {
        title?: string | null;
        subtitle?: string | null;
        description?: string | null;
        image?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroBlock';
      }[]
    | null;
  /**
   * What the experience is about
   */
  experienceSection?:
    | {
        title?: string | null;
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentBlock';
      }[]
    | null;
  /**
   * What makes this specialty special
   */
  specialFeaturesSection?:
    | {
        content?: string | null;
        /**
         * Key highlights
         */
        highlights?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featuresBlock';
      }[]
    | null;
  meta_title?: string | null;
  meta_description?: string | null;
  published_at?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * 🍜 Food and drink items (dishes, beverages, snacks)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food_items".
 */
export interface FoodItem {
  id: number;
  /**
   * Dish name (e.g., "Nasi Lemak", "Char Koay Teow")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "nasi-lemak")
   */
  slug: string;
  /**
   * Names in local languages (Bahasa, Chinese, Tamil)
   */
  localNames?:
    | {
        language: 'ms' | 'zh' | 'hokkien' | 'cantonese' | 'ta' | 'en';
        name: string;
        /**
         * Native script (e.g., 椰浆饭 for Chinese)
         */
        script?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What is this dish? Key characteristics and appeal
   */
  description: string;
  /**
   * Type of food or drink
   */
  category:
    | 'main'
    | 'snack'
    | 'dessert'
    | 'beverage'
    | 'coffee_tea'
    | 'juice'
    | 'traditional_drink'
    | 'condiment'
    | 'breakfast'
    | 'soup'
    | 'noodles'
    | 'rice'
    | 'grilled';
  /**
   * Cultural origin of the dish
   */
  origin: 'malay' | 'chinese' | 'indian' | 'peranakan' | 'thai' | 'indonesian' | 'fusion' | 'international';
  /**
   * Specific region (e.g., "Penang", "Kelantan", "Hainan")
   */
  region?: string | null;
  /**
   * Key ingredients in this dish
   */
  ingredients?:
    | {
        ingredient: string;
        /**
         * Main/defining ingredient
         */
        isMain?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Common allergens present
   */
  allergens?:
    | {
        allergen:
          | 'shellfish'
          | 'fish'
          | 'peanuts'
          | 'tree_nuts'
          | 'soy'
          | 'wheat'
          | 'eggs'
          | 'dairy'
          | 'sesame'
          | 'msg';
        id?: string | null;
      }[]
    | null;
  /**
   * Which dietary options this dish satisfies (e.g., Halal, Vegetarian)
   */
  dietaryTags?: (number | DietaryOption)[] | null;
  /**
   * How spicy is this dish?
   */
  spiceLevel?: ('0' | '1' | '2' | '3' | '4' | '5') | null;
  /**
   * Dominant flavors
   */
  flavorProfile?:
    | {
        flavor: 'sweet' | 'sour' | 'salty' | 'umami' | 'bitter' | 'savory' | 'creamy' | 'tangy';
        id?: string | null;
      }[]
    | null;
  /**
   * Primary cooking method
   */
  preparationMethod?:
    | (
        | 'stir_fried'
        | 'steamed'
        | 'grilled'
        | 'deep_fried'
        | 'braised'
        | 'boiled'
        | 'raw'
        | 'fermented'
        | 'cured'
        | 'mixed'
      )
    | null;
  /**
   * Typical price in MYR (street food range)
   */
  typicalPrice?: number | null;
  /**
   * When is this dish typically available?
   */
  availability?: ('year_round' | 'seasonal' | 'festival' | 'weekend' | 'morning' | 'night') | null;
  /**
   * Main dish photo
   */
  image?: (number | null) | Media;
  /**
   * Additional photos of this dish
   */
  galleryImages?: (number | Media)[] | null;
  /**
   * History, cultural context, stories behind this dish
   */
  culturalSignificance?: string | null;
  /**
   * How is it typically served? Best way to eat it?
   */
  servingSuggestions?: string | null;
  /**
   * Regional or vendor variations of this dish
   */
  popularVariations?: string | null;
  /**
   * What drinks or other dishes pair well with this?
   */
  pairings?: string | null;
  /**
   * Notes about famous vendors, stalls, or restaurants
   */
  vendorNotes?: string | null;
  /**
   * Draft = hidden, Published = available for selection
   */
  status?: ('draft' | 'published') | null;
  /**
   * Mark as signature/must-try dish
   */
  featured?: boolean | null;
  /**
   * Auto-publish at this date/time
   */
  scheduledPublish?: string | null;
  /**
   * When this dish was published
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 📰 Blog posts and articles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  /**
   * Blog post title
   */
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Author of this story
   */
  author: number | User;
  /**
   * Short summary for listing pages (2-3 sentences)
   */
  excerpt?: string | null;
  /**
   * Full blog post content
   */
  content: string;
  /**
   * Publication date
   */
  publishedDate?: string | null;
  /**
   * Main image URL
   */
  featuredImage?: string | null;
  /**
   * Draft = hidden, Published = visible
   */
  status?: ('draft' | 'published') | null;
  /**
   * Workflow approval status
   */
  workflowStatus?: ('draft' | 'in_review' | 'approved' | 'published') | null;
  /**
   * Auto-publish at this date/time (leave empty for immediate)
   */
  scheduledPublish?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * ⭐ Customer reviews and testimonials
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Reviewer name
   */
  author_name: string;
  /**
   * Reviewer location (e.g., "Australia")
   */
  author_location?: string | null;
  /**
   * Star rating (1-5)
   */
  rating: number;
  /**
   * Full review text
   */
  review_text: string;
  /**
   * Short review title/summary
   */
  review_title?: string | null;
  /**
   * Author photo URL (optional)
   */
  author_photo?: string | null;
  /**
   * When review was submitted
   */
  date?: string | null;
  visibility?: {
    /**
     * Verified customer review
     */
    verified?: boolean | null;
    /**
     * Show on homepage
     */
    featured?: boolean | null;
  };
  /**
   * Source platform (Google, TripAdvisor, etc.)
   */
  platform?: string | null;
  /**
   * Workflow approval status
   */
  workflowStatus?: ('draft' | 'in_review' | 'approved' | 'published') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * ❓ Frequently asked questions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer?: string | null;
  category?: string | null;
  /**
   * Sort order (lower numbers first)
   */
  sort_order?: number | null;
  tags?: string | null;
  page_visibility?: string | null;
  tour_id?: number | null;
  /**
   * Workflow approval status
   */
  workflowStatus?: ('draft' | 'in_review' | 'approved' | 'published') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 📰 Press mentions, awards, and media features
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_coverage".
 */
export interface MediaCoverage {
  id: number;
  category?: string | null;
  outlet: string;
  year?: string | null;
  detail?: string | null;
  url?: string | null;
  label?: string | null;
  logo_domain?: string | null;
  highlight?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🏪 Food vendors, stalls, hawkers, and restaurants
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: number;
  /**
   * Vendor/stall/restaurant name
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Type of vendor establishment
   */
  type:
    | 'street_stall'
    | 'hawker_stall'
    | 'food_court'
    | 'kopitiam'
    | 'restaurant'
    | 'pasar_malam'
    | 'pasar_pagi'
    | 'home_kitchen'
    | 'food_truck'
    | 'heritage_shop';
  /**
   * Brief description of this vendor
   */
  description: string;
  /**
   * History, heritage, family story behind this vendor
   */
  history?: string | null;
  /**
   * Year started (e.g., 1965)
   */
  yearEstablished?: number | null;
  /**
   * Which generation runs it now (e.g., "2nd generation", "3rd generation")
   */
  generation?: string | null;
  /**
   * Current owner/chef name
   */
  ownerName?: string | null;
  /**
   * Signature food and drink items this vendor is known for
   */
  specialtyDishes?: (number | FoodItem)[] | null;
  /**
   * Primary cuisine type
   */
  cuisineType: 'malay' | 'chinese' | 'indian' | 'peranakan' | 'thai' | 'indonesian' | 'western' | 'fusion' | 'mixed';
  location: {
    /**
     * Street address
     */
    address?: string | null;
    city: string;
    state:
      | 'kl'
      | 'penang'
      | 'selangor'
      | 'melaka'
      | 'johor'
      | 'perak'
      | 'kelantan'
      | 'terengganu'
      | 'kedah'
      | 'pahang'
      | 'ns'
      | 'perlis'
      | 'sabah'
      | 'sarawak';
    postcode?: string | null;
    country?: string | null;
    /**
     * For map display
     */
    latitude?: number | null;
    /**
     * For map display
     */
    longitude?: number | null;
    /**
     * Nearby landmark for directions (e.g., "opposite Maybank", "next to Chowrasta Market")
     */
    landmark?: string | null;
  };
  /**
   * Operating hours by day
   */
  operatingHours?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday' | 'holiday';
        /**
         * Opening time (e.g., "7:00 AM", "18:00")
         */
        openTime?: string | null;
        /**
         * Closing time
         */
        closeTime?: string | null;
        /**
         * Closed this day
         */
        isClosed?: boolean | null;
        /**
         * Special notes (e.g., "Lunch only", "Morning shift only")
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Regular closed days
   */
  closedOn?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday' | 'holiday';
        id?: string | null;
      }[]
    | null;
  contact?: {
    /**
     * Phone number
     */
    phone?: string | null;
    /**
     * WhatsApp number
     */
    whatsapp?: string | null;
    /**
     * Email address
     */
    email?: string | null;
    /**
     * Website URL
     */
    website?: string | null;
    /**
     * Facebook page URL
     */
    facebook?: string | null;
    /**
     * Instagram handle or URL
     */
    instagram?: string | null;
  };
  /**
   * Price range
   */
  priceRange?: ('budget' | 'moderate' | 'upscale' | 'fine_dining') | null;
  /**
   * Accepted payment methods
   */
  paymentMethods?:
    | {
        method: 'cash' | 'credit_card' | 'debit_card' | 'tng' | 'grabpay' | 'boost' | 'qr_pay' | 'online_banking';
        id?: string | null;
      }[]
    | null;
  /**
   * Available facilities
   */
  facilities?:
    | {
        facility:
          | 'aircon'
          | 'wifi'
          | 'parking'
          | 'wheelchair'
          | 'halal_cert'
          | 'prayer_room'
          | 'outdoor'
          | 'takeaway'
          | 'delivery'
          | 'reservations'
          | 'family';
        id?: string | null;
      }[]
    | null;
  /**
   * Dietary accommodations available
   */
  dietaryOptions?: (number | DietaryOption)[] | null;
  images?: {
    /**
     * Main photo of vendor/stall
     */
    main?: (number | null) | Media;
    /**
     * Additional photos
     */
    gallery?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Full story, anecdotes, interesting facts about this vendor
   */
  story?: string | null;
  /**
   * Awards, recognitions, media features
   */
  awards?:
    | {
        award: string;
        year?: number | null;
        organization?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * TV shows, newspapers, magazines, blogs that featured this vendor
   */
  mediaFeatures?: string | null;
  /**
   * Tips for visitors (e.g., "Arrive early", "Cash only", "Best to try X dish")
   */
  tips?: string | null;
  /**
   * Current operational status
   */
  status?: ('draft' | 'published' | 'closed') | null;
  /**
   * Mark as featured/heritage vendor
   */
  featured?: boolean | null;
  /**
   * Auto-publish at this date/time
   */
  scheduledPublish?: string | null;
  /**
   * When this vendor was published
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 🥗 Dietary-specific landing pages (Vegetarian, Halal, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dietary_landing_pages".
 */
export interface DietaryLandingPage {
  id: number;
  dietary_name: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  icon?: string | null;
  color?: string | null;
  /**
   * Hero section with title, subtitle, description, and image
   */
  heroSection?:
    | {
        title?: string | null;
        subtitle?: string | null;
        description?: string | null;
        image?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroBlock';
      }[]
    | null;
  /**
   * Challenges section for this dietary option
   */
  challengesSection?:
    | {
        title?: string | null;
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentBlock';
      }[]
    | null;
  /**
   * What options are available
   */
  optionsSection?:
    | {
        title?: string | null;
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentBlock';
      }[]
    | null;
  /**
   * Tips and advice
   */
  tipsSection?:
    | {
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'tipsBlock';
      }[]
    | null;
  /**
   * Dishes that are safe to eat
   */
  safeDishesSection?:
    | {
        /**
         * List of safe dishes
         */
        dishes?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'dishListBlock';
      }[]
    | null;
  /**
   * Dishes to avoid for this dietary option
   */
  avoidDishesSection?:
    | {
        /**
         * List of dishes to avoid
         */
        dishes?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'dishListBlock';
      }[]
    | null;
  meta_title?: string | null;
  meta_description?: string | null;
  published_at?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * 📍 Location-based landing pages (Kuala Lumpur, Penang, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "location_landing_pages".
 */
export interface LocationLandingPage {
  id: number;
  status?: ('draft' | 'published') | null;
  location_name: string;
  slug: string;
  /**
   * Hero section with title, subtitle, description, and image
   */
  heroSection?:
    | {
        title?: string | null;
        subtitle?: string | null;
        description?: string | null;
        image?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroBlock';
      }[]
    | null;
  /**
   * Introduction section with image
   */
  introSection?:
    | {
        title?: string | null;
        content?: string | null;
        image?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'introBlock';
      }[]
    | null;
  /**
   * Travel tips: best time to visit, getting around, what to pack
   */
  travelTipsSection?:
    | {
        /**
         * Travel tips (e.g., best time to visit, getting around)
         */
        tips?:
          | {
              title: string;
              content?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'tipsBlock';
      }[]
    | null;
  meta_title?: string | null;
  meta_description?: string | null;
  published_at?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * 📖 About page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_page".
 */
export interface AboutPage {
  id: number;
  seo_title?: string | null;
  seo_description?: string | null;
  /**
   * Page hero with title and subtitle
   */
  heroSection?:
    | {
        title?: string | null;
        subtitle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroBlock';
      }[]
    | null;
  /**
   * Founder story with title and rich text content
   */
  founderStorySection?:
    | {
        title?: string | null;
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'founderStoryBlock';
      }[]
    | null;
  /**
   * Key statistics about Simply Enak
   */
  statsSection?:
    | {
        /**
         * Stat items (number + label)
         */
        stats?:
          | {
              number: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statsBlock';
      }[]
    | null;
  /**
   * Company history timeline
   */
  timelineSection?:
    | {
        /**
         * Timeline events (year, title, description)
         */
        events?:
          | {
              year: string;
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'timelineBlock';
      }[]
    | null;
  /**
   * Company philosophy/mission
   */
  philosophySection?:
    | {
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'philosophyBlock';
      }[]
    | null;
  /**
   * Team members
   */
  teamSection?:
    | {
        /**
         * Team members
         */
        members?:
          | {
              name: string;
              role?: string | null;
              specialty?: string | null;
              description?: string | null;
              photo?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'teamBlock';
      }[]
    | null;
  parent?: (number | null) | AboutPage;
  breadcrumbs?:
    | {
        doc?: (number | null) | AboutPage;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📞 Contact page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_page".
 */
export interface ContactPage {
  id: number;
  seo_title?: string | null;
  seo_description?: string | null;
  /**
   * Page hero with title and subtitle
   */
  heroSection?:
    | {
        title?: string | null;
        subtitle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroBlock';
      }[]
    | null;
  /**
   * Introduction text before contact details
   */
  contactIntroSection?:
    | {
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'introBlock';
      }[]
    | null;
  /**
   * Email, phone, WhatsApp contact details
   */
  contactChannelsSection?:
    | {
        /**
         * Contact channels (email, phone, WhatsApp, etc.)
         */
        channels?:
          | {
              type: 'email' | 'phone' | 'whatsapp' | 'website' | 'other';
              value: string;
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'channelsBlock';
      }[]
    | null;
  /**
   * Social media links
   */
  socialLinksSection?:
    | {
        /**
         * Social media links
         */
        links?:
          | {
              platform: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'socialBlock';
      }[]
    | null;
  /**
   * FAQ content for contact page
   */
  faqSection?:
    | {
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqBlock';
      }[]
    | null;
  parent?: (number | null) | ContactPage;
  breadcrumbs?:
    | {
        doc?: (number | null) | ContactPage;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🎉 Thank you pages for form submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "thank_you_pages".
 */
export interface ThankYouPage {
  id: number;
  /**
   * Page title (e.g., "Thank You - Contact Form")
   */
  title: string;
  /**
   * What form submission this page is for
   */
  type: 'contact' | 'tour_inquiry' | 'feedback' | 'newsletter' | 'booking' | 'custom';
  /**
   * URL path (e.g., "thank-you-contact")
   */
  slug: string;
  /**
   * Publish when ready
   */
  status?: ('draft' | 'published') | null;
  heroSection?: {
    /**
     * Main heading
     */
    heading?: string | null;
    /**
     * Subheading text
     */
    subheading?: string | null;
    /**
     * Emoji or icon
     */
    icon?: string | null;
  };
  /**
   * Main thank you message
   */
  message?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What happens next (bullet points)
   */
  nextSteps?:
    | {
        step: string;
        id?: string | null;
      }[]
    | null;
  contactInfo?: {
    /**
     * Show contact information
     */
    showContact?: boolean | null;
    /**
     * Contact email (optional)
     */
    email?: string | null;
    /**
     * Contact phone (optional)
     */
    phone?: string | null;
    /**
     * Expected response time
     */
    responseTime?: string | null;
  };
  ctaSection?: {
    /**
     * Show call-to-action buttons
     */
    showCta?: boolean | null;
    /**
     * Buttons to show (e.g., "Browse Tours")
     */
    ctaButtons?:
      | {
          text: string;
          url: string;
          variant?: ('primary' | 'secondary') | null;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    /**
     * SEO title
     */
    metaTitle?: string | null;
    /**
     * SEO description
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * 🏠 Home page content and sections
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_page".
 */
export interface HomePage {
  id: number;
  /**
   * Hero section with title, subtitle, badges, and background image
   */
  heroSection?:
    | {
        title?: string | null;
        highlight?: string | null;
        titleEnd?: string | null;
        subtitle?: string | null;
        description?: string | null;
        priceInfo?: string | null;
        bgImage?: string | null;
        /**
         * Trust badges (e.g., "40+ Heritage Vendors", "Since 2011")
         */
        badges?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroBlock';
      }[]
    | null;
  /**
   * Brand belief/mission statement section
   */
  manifestoSection?:
    | {
        eyebrow?: string | null;
        headline?: string | null;
        tagline?: string | null;
        body?: string | null;
        attributionRole?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'manifestoBlock';
      }[]
    | null;
  /**
   * Three core pillars: People, Food, Place
   */
  pillarsSection?:
    | {
        intro?: string | null;
        /**
         * The three pillars: People, Food, Place
         */
        pillars?:
          | {
              label?: string | null;
              heading?: string | null;
              body?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pillarsBlock';
      }[]
    | null;
  /**
   * Vendor showcase section with links
   */
  vendorsSection?:
    | {
        eyebrow?: string | null;
        title?: string | null;
        subtitle?: string | null;
        /**
         * CTA links (e.g., "Meet on Tour", "Read Stories")
         */
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'vendorsBlock';
      }[]
    | null;
  /**
   * Tour category selector section
   */
  segmentsSection?:
    | {
        heading?: string | null;
        subheading?: string | null;
        viewAllLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'segmentsBlock';
      }[]
    | null;
  /**
   * About Simply Enak teaser section
   */
  aboutSection?:
    | {
        eyebrow?: string | null;
        title?: string | null;
        subtitle?: string | null;
        description?: string | null;
        heritage?: string | null;
        image?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutBlock';
      }[]
    | null;
  /**
   * "What to Expect" stats section
   */
  expectSection?:
    | {
        title?: string | null;
        subtitle?: string | null;
        /**
         * Stat items (number, heading, body)
         */
        stats?:
          | {
              number?: string | null;
              heading?: string | null;
              body?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statsBlock';
      }[]
    | null;
  /**
   * Call-to-action section blocks
   */
  ctaSection?:
    | {
        eyebrow?: string | null;
        title: string;
        subtitle?: string | null;
        /**
         * Trust signals
         */
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * CTA buttons
         */
        buttons?:
          | {
              label: string;
              url: string;
              variant?: ('primary' | 'secondary' | 'whatsapp') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaBlock';
      }[]
    | null;
  /**
   * Array of FAQ items for home page
   */
  faqs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  meta_title?: string | null;
  meta_description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📜 Legal pages (Privacy Policy, Terms, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_pages".
 */
export interface LegalPage {
  id: number;
  /**
   * URL slug for this legal page (e.g., privacy-policy, terms-of-service)
   */
  slug: string;
  /**
   * Publication status
   */
  status?: ('draft' | 'published') | null;
  /**
   * Page headline/title (e.g., Privacy Policy, Terms of Service)
   */
  headline: string;
  /**
   * Full page content in rich text format
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * SEO meta title
   */
  meta_title?: string | null;
  /**
   * SEO meta description
   */
  meta_description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🧭 Manage site navigation menus
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  /**
   * Menu name (e.g., "Main Navigation", "Footer Menu")
   */
  name: string;
  /**
   * Where this menu appears on the site
   */
  location: 'top' | 'mobile' | 'footer' | 'sub_page';
  /**
   * Menu items — label and URL for each link
   */
  items: {
    label: string;
    url: string;
    openInNewTab?: boolean | null;
    /**
     * Display order (lower = first)
     */
    order?: number | null;
    id?: string | null;
  }[];
  /**
   * Auto-calculated from items array
   */
  itemCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🧳 Traveler type references (Couples, Solo, Family, Foodie)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel_types".
 */
export interface TravelType {
  id: number;
  name: string;
  slug: string;
  /**
   * Emoji or icon name
   */
  icon?: string | null;
  /**
   * UI color hex code
   */
  color?: string | null;
  description?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ⭐ Specialty experience references (Heritage, Street Food, Night Tour, Market)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialty_experiences".
 */
export interface SpecialtyExperience {
  id: number;
  name: string;
  slug: string;
  /**
   * Emoji or icon name
   */
  icon?: string | null;
  /**
   * UI color hex code
   */
  color?: string | null;
  description?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📍 Location references (Kuala Lumpur, Penang, Ipoh)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  slug: string;
  /**
   * Emoji or icon name
   */
  icon?: string | null;
  /**
   * UI color hex code
   */
  color?: string | null;
  description?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🌐 Manage all translations in one place
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations".
 */
export interface Translation {
  id: number;
  /**
   * Descriptive label (e.g., "Flavours of Malaysia - Malay Translation")
   */
  label: string;
  /**
   * Language for this translation
   */
  locale: 'en' | 'ms' | 'zh' | 'de' | 'es' | 'fr' | 'nl' | 'ja' | 'pt' | 'ru';
  /**
   * Which collection this translation belongs to
   */
  collection:
    | 'tours'
    | 'stories'
    | 'testimonials'
    | 'faqs'
    | 'media_coverage'
    | 'dietary_landing_pages'
    | 'specialty_landing_pages'
    | 'travel_type_landing_pages'
    | 'location_landing_pages'
    | 'home_page'
    | 'legal_pages';
  /**
   * The original content item being translated
   */
  parent:
    | {
        relationTo: 'tours';
        value: number | Tour;
      }
    | {
        relationTo: 'stories';
        value: number | Story;
      }
    | {
        relationTo: 'testimonials';
        value: number | Testimonial;
      }
    | {
        relationTo: 'faqs';
        value: number | Faq;
      }
    | {
        relationTo: 'media_coverage';
        value: number | MediaCoverage;
      }
    | {
        relationTo: 'dietary_landing_pages';
        value: number | DietaryLandingPage;
      }
    | {
        relationTo: 'specialty_landing_pages';
        value: number | SpecialtyLandingPage;
      }
    | {
        relationTo: 'travel_type_landing_pages';
        value: number | TravelTypeLandingPage;
      }
    | {
        relationTo: 'location_landing_pages';
        value: number | LocationLandingPage;
      }
    | {
        relationTo: 'home_page';
        value: number | HomePage;
      }
    | {
        relationTo: 'legal_pages';
        value: number | LegalPage;
      };
  /**
   * Translation workflow status
   */
  status?: ('draft' | 'in_translation' | 'ready_for_review' | 'published') | null;
  /**
   * Who translated this (name or agency)
   */
  translator?: string | null;
  /**
   * When translation was completed
   */
  translatedAt?: string | null;
  /**
   * Translated content fields
   */
  fields?: {
    /**
     * Name/Title translation
     */
    name?: string | null;
    /**
     * Tagline translation
     */
    tagline?: string | null;
    /**
     * Short description translation
     */
    shortDescription?: string | null;
    /**
     * Full description translation
     */
    fullDescription?: string | null;
    /**
     * Main content (for stories)
     */
    content?: string | null;
    /**
     * Excerpt/summary translation
     */
    excerpt?: string | null;
    /**
     * Question (for FAQs)
     */
    question?: string | null;
    /**
     * Answer (for FAQs)
     */
    answer?: string | null;
    /**
     * Review text (for testimonials)
     */
    reviewText?: string | null;
    /**
     * Review title (for testimonials)
     */
    reviewTitle?: string | null;
    /**
     * Hero title (for landing pages)
     */
    heroTitle?: string | null;
    /**
     * Hero subtitle (for landing pages)
     */
    heroSubtitle?: string | null;
    /**
     * Hero description (for landing pages)
     */
    heroDescription?: string | null;
  };
  /**
   * SEO translations
   */
  seo?: {
    /**
     * Meta title translation
     */
    metaTitle?: string | null;
    /**
     * Meta description translation
     */
    metaDescription?: string | null;
  };
  /**
   * Internal notes for translators
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Global site settings and configuration
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_settings".
 */
export interface SiteSetting {
  id: number;
  site_name?: string | null;
  tagline?: string | null;
  description?: string | null;
  hero_title?: string | null;
  hero_subtitle?: string | null;
  hero_description?: string | null;
  hero_image?: string | null;
  booking_url?: string | null;
  social_media?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  whatsapp_number?: string | null;
  address?: string | null;
  meta_title?: string | null;
  meta_description?: string | null;
  /**
   * Main navigation menu items (JSON array of {label, url})
   */
  main_navigation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Mobile navigation menu items (JSON array of {label, url})
   */
  mobile_navigation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Footer navigation menu items (JSON array of {label, url})
   */
  footer_navigation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Copyright text displayed in footer
   */
  footer_copyright_text?: string | null;
  /**
   * Sub-page menus (JSON object with menu keys and arrays of items)
   */
  sub_page_menus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * 🔄 Manage URL redirects (301/302)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'tours';
          value: number | Tour;
        } | null)
      | ({
          relationTo: 'stories';
          value: number | Story;
        } | null)
      | ({
          relationTo: 'dietary_landing_pages';
          value: number | DietaryLandingPage;
        } | null)
      | ({
          relationTo: 'specialty_landing_pages';
          value: number | SpecialtyLandingPage;
        } | null)
      | ({
          relationTo: 'travel_type_landing_pages';
          value: number | TravelTypeLandingPage;
        } | null)
      | ({
          relationTo: 'location_landing_pages';
          value: number | LocationLandingPage;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'tours';
        value: number | Tour;
      }
    | {
        relationTo: 'stories';
        value: number | Story;
      }
    | {
        relationTo: 'faqs';
        value: number | Faq;
      }
    | {
        relationTo: 'testimonials';
        value: number | Testimonial;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media_coverage';
        value: number | MediaCoverage;
      } | null)
    | ({
        relationTo: 'dietary_options';
        value: number | DietaryOption;
      } | null)
    | ({
        relationTo: 'food_items';
        value: number | FoodItem;
      } | null)
    | ({
        relationTo: 'vendors';
        value: number | Vendor;
      } | null)
    | ({
        relationTo: 'dietary_landing_pages';
        value: number | DietaryLandingPage;
      } | null)
    | ({
        relationTo: 'specialty_landing_pages';
        value: number | SpecialtyLandingPage;
      } | null)
    | ({
        relationTo: 'travel_type_landing_pages';
        value: number | TravelTypeLandingPage;
      } | null)
    | ({
        relationTo: 'location_landing_pages';
        value: number | LocationLandingPage;
      } | null)
    | ({
        relationTo: 'about_page';
        value: number | AboutPage;
      } | null)
    | ({
        relationTo: 'contact_page';
        value: number | ContactPage;
      } | null)
    | ({
        relationTo: 'thank_you_pages';
        value: number | ThankYouPage;
      } | null)
    | ({
        relationTo: 'home_page';
        value: number | HomePage;
      } | null)
    | ({
        relationTo: 'legal_pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'travel_types';
        value: number | TravelType;
      } | null)
    | ({
        relationTo: 'specialty_experiences';
        value: number | SpecialtyExperience;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'translations';
        value: number | Translation;
      } | null)
    | ({
        relationTo: 'site_settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  fullName?: T;
  department?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  usage?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  shortDescription?: T;
  fullDescription?: T;
  price?: T;
  currency?: T;
  duration?: T;
  durationMinutes?: T;
  location?: T;
  meetingPoint?: T;
  maxParticipants?: T;
  minParticipants?: T;
  dietaryOptions?: T;
  travelTypes?: T;
  specialtyExperiences?: T;
  foodItems?: T;
  tailoredAvailable?: T;
  tailoredNotes?: T;
  heroImage?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  whatsIncluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  whatsExcluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        highlight?: T;
        id?: T;
      };
  bookingUrl?: T;
  instantConfirmation?: T;
  scheduledPublish?: T;
  featured?: T;
  popular?: T;
  new?: T;
  publishedAt?: T;
  status?: T;
  workflowStatus?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  excerpt?: T;
  content?: T;
  publishedDate?: T;
  featuredImage?: T;
  status?: T;
  workflowStatus?: T;
  scheduledPublish?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author_name?: T;
  author_location?: T;
  rating?: T;
  review_text?: T;
  review_title?: T;
  author_photo?: T;
  date?: T;
  visibility?:
    | T
    | {
        verified?: T;
        featured?: T;
      };
  platform?: T;
  workflowStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  sort_order?: T;
  tags?: T;
  page_visibility?: T;
  tour_id?: T;
  workflowStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_coverage_select".
 */
export interface MediaCoverageSelect<T extends boolean = true> {
  category?: T;
  outlet?: T;
  year?: T;
  detail?: T;
  url?: T;
  label?: T;
  logo_domain?: T;
  highlight?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dietary_options_select".
 */
export interface DietaryOptionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  color?: T;
  description?: T;
  status?: T;
  scheduledPublish?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food_items_select".
 */
export interface FoodItemsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  localNames?:
    | T
    | {
        language?: T;
        name?: T;
        script?: T;
        id?: T;
      };
  description?: T;
  category?: T;
  origin?: T;
  region?: T;
  ingredients?:
    | T
    | {
        ingredient?: T;
        isMain?: T;
        id?: T;
      };
  allergens?:
    | T
    | {
        allergen?: T;
        id?: T;
      };
  dietaryTags?: T;
  spiceLevel?: T;
  flavorProfile?:
    | T
    | {
        flavor?: T;
        id?: T;
      };
  preparationMethod?: T;
  typicalPrice?: T;
  availability?: T;
  image?: T;
  galleryImages?: T;
  culturalSignificance?: T;
  servingSuggestions?: T;
  popularVariations?: T;
  pairings?: T;
  vendorNotes?: T;
  status?: T;
  featured?: T;
  scheduledPublish?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  history?: T;
  yearEstablished?: T;
  generation?: T;
  ownerName?: T;
  specialtyDishes?: T;
  cuisineType?: T;
  location?:
    | T
    | {
        address?: T;
        city?: T;
        state?: T;
        postcode?: T;
        country?: T;
        latitude?: T;
        longitude?: T;
        landmark?: T;
      };
  operatingHours?:
    | T
    | {
        day?: T;
        openTime?: T;
        closeTime?: T;
        isClosed?: T;
        notes?: T;
        id?: T;
      };
  closedOn?:
    | T
    | {
        day?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        whatsapp?: T;
        email?: T;
        website?: T;
        facebook?: T;
        instagram?: T;
      };
  priceRange?: T;
  paymentMethods?:
    | T
    | {
        method?: T;
        id?: T;
      };
  facilities?:
    | T
    | {
        facility?: T;
        id?: T;
      };
  dietaryOptions?: T;
  images?:
    | T
    | {
        main?: T;
        gallery?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  story?: T;
  awards?:
    | T
    | {
        award?: T;
        year?: T;
        organization?: T;
        id?: T;
      };
  mediaFeatures?: T;
  tips?: T;
  status?: T;
  featured?: T;
  scheduledPublish?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dietary_landing_pages_select".
 */
export interface DietaryLandingPagesSelect<T extends boolean = true> {
  dietary_name?: T;
  slug?: T;
  status?: T;
  icon?: T;
  color?: T;
  heroSection?:
    | T
    | {
        heroBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  challengesSection?:
    | T
    | {
        contentBlock?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  optionsSection?:
    | T
    | {
        contentBlock?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  tipsSection?:
    | T
    | {
        tipsBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  safeDishesSection?:
    | T
    | {
        dishListBlock?:
          | T
          | {
              dishes?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  avoidDishesSection?:
    | T
    | {
        dishListBlock?:
          | T
          | {
              dishes?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta_title?: T;
  meta_description?: T;
  published_at?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialty_landing_pages_select".
 */
export interface SpecialtyLandingPagesSelect<T extends boolean = true> {
  specialty_name?: T;
  slug?: T;
  status?: T;
  icon?: T;
  color?: T;
  heroSection?:
    | T
    | {
        heroBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  experienceSection?:
    | T
    | {
        contentBlock?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  specialFeaturesSection?:
    | T
    | {
        featuresBlock?:
          | T
          | {
              content?: T;
              highlights?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta_title?: T;
  meta_description?: T;
  published_at?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel_type_landing_pages_select".
 */
export interface TravelTypeLandingPagesSelect<T extends boolean = true> {
  travel_type_name?: T;
  slug?: T;
  status?: T;
  icon?: T;
  color?: T;
  heroSection?:
    | T
    | {
        heroBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  whyPerfectSection?:
    | T
    | {
        contentBlock?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  expectSection?:
    | T
    | {
        contentBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  tipsSection?:
    | T
    | {
        tipsBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  suitableToursSection?:
    | T
    | {
        tourListBlock?:
          | T
          | {
              tours?:
                | T
                | {
                    slug?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  keyFeaturesSection?:
    | T
    | {
        featuresBlock?:
          | T
          | {
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta_title?: T;
  meta_description?: T;
  published_at?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "location_landing_pages_select".
 */
export interface LocationLandingPagesSelect<T extends boolean = true> {
  status?: T;
  location_name?: T;
  slug?: T;
  heroSection?:
    | T
    | {
        heroBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  introSection?:
    | T
    | {
        introBlock?:
          | T
          | {
              title?: T;
              content?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  travelTipsSection?:
    | T
    | {
        tipsBlock?:
          | T
          | {
              tips?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta_title?: T;
  meta_description?: T;
  published_at?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  seo_title?: T;
  seo_description?: T;
  heroSection?:
    | T
    | {
        heroBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
      };
  founderStorySection?:
    | T
    | {
        founderStoryBlock?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  statsSection?:
    | T
    | {
        statsBlock?:
          | T
          | {
              stats?:
                | T
                | {
                    number?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  timelineSection?:
    | T
    | {
        timelineBlock?:
          | T
          | {
              events?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  philosophySection?:
    | T
    | {
        philosophyBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  teamSection?:
    | T
    | {
        teamBlock?:
          | T
          | {
              members?:
                | T
                | {
                    name?: T;
                    role?: T;
                    specialty?: T;
                    description?: T;
                    photo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  seo_title?: T;
  seo_description?: T;
  heroSection?:
    | T
    | {
        heroBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
      };
  contactIntroSection?:
    | T
    | {
        introBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  contactChannelsSection?:
    | T
    | {
        channelsBlock?:
          | T
          | {
              channels?:
                | T
                | {
                    type?: T;
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  socialLinksSection?:
    | T
    | {
        socialBlock?:
          | T
          | {
              links?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  faqSection?:
    | T
    | {
        faqBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "thank_you_pages_select".
 */
export interface ThankYouPagesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  slug?: T;
  status?: T;
  heroSection?:
    | T
    | {
        heading?: T;
        subheading?: T;
        icon?: T;
      };
  message?: T;
  nextSteps?:
    | T
    | {
        step?: T;
        id?: T;
      };
  contactInfo?:
    | T
    | {
        showContact?: T;
        email?: T;
        phone?: T;
        responseTime?: T;
      };
  ctaSection?:
    | T
    | {
        showCta?: T;
        ctaButtons?:
          | T
          | {
              text?: T;
              url?: T;
              variant?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        heroBlock?:
          | T
          | {
              title?: T;
              highlight?: T;
              titleEnd?: T;
              subtitle?: T;
              description?: T;
              priceInfo?: T;
              bgImage?: T;
              badges?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  manifestoSection?:
    | T
    | {
        manifestoBlock?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              tagline?: T;
              body?: T;
              attributionRole?: T;
              id?: T;
              blockName?: T;
            };
      };
  pillarsSection?:
    | T
    | {
        pillarsBlock?:
          | T
          | {
              intro?: T;
              pillars?:
                | T
                | {
                    label?: T;
                    heading?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  vendorsSection?:
    | T
    | {
        vendorsBlock?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  segmentsSection?:
    | T
    | {
        segmentsBlock?:
          | T
          | {
              heading?: T;
              subheading?: T;
              viewAllLabel?: T;
              id?: T;
              blockName?: T;
            };
      };
  aboutSection?:
    | T
    | {
        aboutBlock?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              description?: T;
              heritage?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  expectSection?:
    | T
    | {
        statsBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              stats?:
                | T
                | {
                    number?: T;
                    heading?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  ctaSection?:
    | T
    | {
        ctaBlock?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  faqs?: T;
  meta_title?: T;
  meta_description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  status?: T;
  headline?: T;
  content?: T;
  meta_title?: T;
  meta_description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  items?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        order?: T;
        id?: T;
      };
  itemCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel_types_select".
 */
export interface TravelTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  color?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialty_experiences_select".
 */
export interface SpecialtyExperiencesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  color?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  color?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations_select".
 */
export interface TranslationsSelect<T extends boolean = true> {
  label?: T;
  locale?: T;
  collection?: T;
  parent?: T;
  status?: T;
  translator?: T;
  translatedAt?: T;
  fields?:
    | T
    | {
        name?: T;
        tagline?: T;
        shortDescription?: T;
        fullDescription?: T;
        content?: T;
        excerpt?: T;
        question?: T;
        answer?: T;
        reviewText?: T;
        reviewTitle?: T;
        heroTitle?: T;
        heroSubtitle?: T;
        heroDescription?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  site_name?: T;
  tagline?: T;
  description?: T;
  hero_title?: T;
  hero_subtitle?: T;
  hero_description?: T;
  hero_image?: T;
  booking_url?: T;
  social_media?: T;
  contact_email?: T;
  contact_phone?: T;
  whatsapp_number?: T;
  address?: T;
  meta_title?: T;
  meta_description?: T;
  main_navigation?: T;
  mobile_navigation?: T;
  footer_navigation?: T;
  footer_copyright_text?: T;
  sub_page_menus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'users'
      | 'media'
      | 'tours'
      | 'stories'
      | 'testimonials'
      | 'faqs'
      | 'media_coverage'
      | 'dietary_options'
      | 'food_items'
      | 'vendors'
      | 'dietary_landing_pages'
      | 'specialty_landing_pages'
      | 'travel_type_landing_pages'
      | 'location_landing_pages'
      | 'about_page'
      | 'contact_page'
      | 'thank_you_pages'
      | 'home_page'
      | 'legal_pages'
      | 'menus'
      | 'travel_types'
      | 'specialty_experiences'
      | 'locations'
      | 'translations'
      | 'site_settings'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}