/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  type AnyPgColumn,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', [
  'admin',
  'editor',
  'translator',
  'reviewer',
])
export const enum_tours_status = pgEnum('enum_tours_status', ['draft', 'published'])
export const enum_tours_workflow_status = pgEnum('enum_tours_workflow_status', [
  'draft',
  'in_review',
  'approved',
  'published',
])
export const enum__tours_v_version_status = pgEnum('enum__tours_v_version_status', [
  'draft',
  'published',
])
export const enum__tours_v_version_workflow_status = pgEnum(
  'enum__tours_v_version_workflow_status',
  ['draft', 'in_review', 'approved', 'published'],
)
export const enum_stories_status = pgEnum('enum_stories_status', ['draft', 'published'])
export const enum_stories_workflow_status = pgEnum('enum_stories_workflow_status', [
  'draft',
  'in_review',
  'approved',
  'published',
])
export const enum__stories_v_version_status = pgEnum('enum__stories_v_version_status', [
  'draft',
  'published',
])
export const enum__stories_v_version_workflow_status = pgEnum(
  'enum__stories_v_version_workflow_status',
  ['draft', 'in_review', 'approved', 'published'],
)
export const enum_testimonials_workflow_status = pgEnum('enum_testimonials_workflow_status', [
  'draft',
  'in_review',
  'approved',
  'published',
])
export const enum_testimonials_status = pgEnum('enum_testimonials_status', ['draft', 'published'])
export const enum__testimonials_v_version_workflow_status = pgEnum(
  'enum__testimonials_v_version_workflow_status',
  ['draft', 'in_review', 'approved', 'published'],
)
export const enum__testimonials_v_version_status = pgEnum('enum__testimonials_v_version_status', [
  'draft',
  'published',
])
export const enum_faqs_workflow_status = pgEnum('enum_faqs_workflow_status', [
  'draft',
  'in_review',
  'approved',
  'published',
])
export const enum_faqs_status = pgEnum('enum_faqs_status', ['draft', 'published'])
export const enum__faqs_v_version_workflow_status = pgEnum('enum__faqs_v_version_workflow_status', [
  'draft',
  'in_review',
  'approved',
  'published',
])
export const enum__faqs_v_version_status = pgEnum('enum__faqs_v_version_status', [
  'draft',
  'published',
])
export const enum_media_coverage_status = pgEnum('enum_media_coverage_status', [
  'draft',
  'published',
])
export const enum_dietary_landing_pages_status = pgEnum('enum_dietary_landing_pages_status', [
  'draft',
  'published',
])
export const enum_specialty_landing_pages_status = pgEnum('enum_specialty_landing_pages_status', [
  'draft',
  'published',
])
export const enum_travel_type_landing_pages_status = pgEnum(
  'enum_travel_type_landing_pages_status',
  ['draft', 'published'],
)
export const enum_location_landing_pages_status = pgEnum('enum_location_landing_pages_status', [
  'draft',
  'published',
])
export const enum_thank_you_pages_cta_section_cta_buttons_variant = pgEnum(
  'enum_thank_you_pages_cta_section_cta_buttons_variant',
  ['primary', 'secondary'],
)
export const enum_thank_you_pages_type = pgEnum('enum_thank_you_pages_type', [
  'contact',
  'tour_inquiry',
  'feedback',
  'newsletter',
  'booking',
  'custom',
])
export const enum_thank_you_pages_status = pgEnum('enum_thank_you_pages_status', [
  'draft',
  'published',
])
export const enum_translations_locale = pgEnum('enum_translations_locale', [
  'en',
  'ms',
  'zh',
  'de',
  'es',
  'fr',
  'nl',
  'ja',
  'pt',
  'ru',
])
export const enum_translations_collection = pgEnum('enum_translations_collection', [
  'tours',
  'stories',
  'testimonials',
  'faqs',
  'media_coverage',
  'dietary_landing_pages',
  'specialty_landing_pages',
  'travel_type_landing_pages',
  'location_landing_pages',
])
export const enum_translations_status = pgEnum('enum_translations_status', [
  'draft',
  'in_translation',
  'ready_for_review',
  'published',
])
export const enum_redirects_to_type = pgEnum('enum_redirects_to_type', ['reference', 'custom'])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    role: enum_users_role('role').notNull().default('editor'),
    fullName: varchar('full_name'),
    department: varchar('department'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt'),
    caption: varchar('caption'),
    usage: varchar('usage'),
    prefix: varchar('prefix').default('payload-media'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    sizes_thumbnail_url: varchar('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width', { mode: 'number' }),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height', { mode: 'number' }),
    sizes_thumbnail_mimeType: varchar('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize', { mode: 'number' }),
    sizes_thumbnail_filename: varchar('sizes_thumbnail_filename'),
    sizes_medium_url: varchar('sizes_medium_url'),
    sizes_medium_width: numeric('sizes_medium_width', { mode: 'number' }),
    sizes_medium_height: numeric('sizes_medium_height', { mode: 'number' }),
    sizes_medium_mimeType: varchar('sizes_medium_mime_type'),
    sizes_medium_filesize: numeric('sizes_medium_filesize', { mode: 'number' }),
    sizes_medium_filename: varchar('sizes_medium_filename'),
    sizes_large_url: varchar('sizes_large_url'),
    sizes_large_width: numeric('sizes_large_width', { mode: 'number' }),
    sizes_large_height: numeric('sizes_large_height', { mode: 'number' }),
    sizes_large_mimeType: varchar('sizes_large_mime_type'),
    sizes_large_filesize: numeric('sizes_large_filesize', { mode: 'number' }),
    sizes_large_filename: varchar('sizes_large_filename'),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
    index('media_sizes_thumbnail_sizes_thumbnail_filename_idx').on(
      columns.sizes_thumbnail_filename,
    ),
    index('media_sizes_medium_sizes_medium_filename_idx').on(columns.sizes_medium_filename),
    index('media_sizes_large_sizes_large_filename_idx').on(columns.sizes_large_filename),
  ],
)

export const tours_dietary_options = pgTable(
  'tours_dietary_options',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    option: varchar('option'),
  },
  (columns) => [
    index('tours_dietary_options_order_idx').on(columns._order),
    index('tours_dietary_options_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours.id],
      name: 'tours_dietary_options_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_travel_types = pgTable(
  'tours_travel_types',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    type: varchar('type'),
  },
  (columns) => [
    index('tours_travel_types_order_idx').on(columns._order),
    index('tours_travel_types_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours.id],
      name: 'tours_travel_types_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_specialty_experiences = pgTable(
  'tours_specialty_experiences',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    experience: varchar('experience'),
  },
  (columns) => [
    index('tours_specialty_experiences_order_idx').on(columns._order),
    index('tours_specialty_experiences_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours.id],
      name: 'tours_specialty_experiences_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_gallery_images = pgTable(
  'tours_gallery_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: varchar('image'),
  },
  (columns) => [
    index('tours_gallery_images_order_idx').on(columns._order),
    index('tours_gallery_images_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours.id],
      name: 'tours_gallery_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_whats_included = pgTable(
  'tours_whats_included',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    item: varchar('item'),
  },
  (columns) => [
    index('tours_whats_included_order_idx').on(columns._order),
    index('tours_whats_included_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours.id],
      name: 'tours_whats_included_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_whats_excluded = pgTable(
  'tours_whats_excluded',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    item: varchar('item'),
  },
  (columns) => [
    index('tours_whats_excluded_order_idx').on(columns._order),
    index('tours_whats_excluded_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours.id],
      name: 'tours_whats_excluded_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_highlights = pgTable(
  'tours_highlights',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    highlight: varchar('highlight'),
  },
  (columns) => [
    index('tours_highlights_order_idx').on(columns._order),
    index('tours_highlights_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours.id],
      name: 'tours_highlights_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours = pgTable(
  'tours',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    slug: varchar('slug'),
    tagline: varchar('tagline'),
    shortDescription: varchar('short_description'),
    fullDescription: varchar('full_description'),
    price: numeric('price', { mode: 'number' }),
    currency: varchar('currency').default('MYR'),
    duration: varchar('duration'),
    durationMinutes: numeric('duration_minutes', { mode: 'number' }),
    location: varchar('location'),
    meetingPoint: varchar('meeting_point'),
    maxParticipants: numeric('max_participants', { mode: 'number' }),
    minParticipants: numeric('min_participants', { mode: 'number' }).default(2),
    tailoredAvailable: boolean('tailored_available').default(false),
    tailoredNotes: varchar('tailored_notes'),
    heroImage: varchar('hero_image'),
    bookingUrl: varchar('booking_url'),
    instantConfirmation: boolean('instant_confirmation').default(true),
    metaTitle: varchar('meta_title'),
    metaDescription: varchar('meta_description'),
    featured: boolean('featured').default(false),
    popular: boolean('popular').default(false),
    new: boolean('new').default(false),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    status: enum_tours_status('status').default('draft'),
    workflowStatus: enum_tours_workflow_status('workflow_status').default('draft'),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    meta_image: integer('meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_tours_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('tours_slug_idx').on(columns.slug),
    index('tours_meta_meta_image_idx').on(columns.meta_image),
    index('tours_updated_at_idx').on(columns.updatedAt),
    index('tours_created_at_idx').on(columns.createdAt),
    index('tours__status_idx').on(columns._status),
  ],
)

export const _tours_v_version_dietary_options = pgTable(
  '_tours_v_version_dietary_options',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    option: varchar('option'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_tours_v_version_dietary_options_order_idx').on(columns._order),
    index('_tours_v_version_dietary_options_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_tours_v.id],
      name: '_tours_v_version_dietary_options_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _tours_v_version_travel_types = pgTable(
  '_tours_v_version_travel_types',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    type: varchar('type'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_tours_v_version_travel_types_order_idx').on(columns._order),
    index('_tours_v_version_travel_types_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_tours_v.id],
      name: '_tours_v_version_travel_types_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _tours_v_version_specialty_experiences = pgTable(
  '_tours_v_version_specialty_experiences',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    experience: varchar('experience'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_tours_v_version_specialty_experiences_order_idx').on(columns._order),
    index('_tours_v_version_specialty_experiences_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_tours_v.id],
      name: '_tours_v_version_specialty_experiences_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _tours_v_version_gallery_images = pgTable(
  '_tours_v_version_gallery_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    image: varchar('image'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_tours_v_version_gallery_images_order_idx').on(columns._order),
    index('_tours_v_version_gallery_images_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_tours_v.id],
      name: '_tours_v_version_gallery_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _tours_v_version_whats_included = pgTable(
  '_tours_v_version_whats_included',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    item: varchar('item'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_tours_v_version_whats_included_order_idx').on(columns._order),
    index('_tours_v_version_whats_included_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_tours_v.id],
      name: '_tours_v_version_whats_included_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _tours_v_version_whats_excluded = pgTable(
  '_tours_v_version_whats_excluded',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    item: varchar('item'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_tours_v_version_whats_excluded_order_idx').on(columns._order),
    index('_tours_v_version_whats_excluded_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_tours_v.id],
      name: '_tours_v_version_whats_excluded_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _tours_v_version_highlights = pgTable(
  '_tours_v_version_highlights',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    highlight: varchar('highlight'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_tours_v_version_highlights_order_idx').on(columns._order),
    index('_tours_v_version_highlights_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_tours_v.id],
      name: '_tours_v_version_highlights_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _tours_v = pgTable(
  '_tours_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => tours.id, {
      onDelete: 'set null',
    }),
    version_name: varchar('version_name'),
    version_slug: varchar('version_slug'),
    version_tagline: varchar('version_tagline'),
    version_shortDescription: varchar('version_short_description'),
    version_fullDescription: varchar('version_full_description'),
    version_price: numeric('version_price', { mode: 'number' }),
    version_currency: varchar('version_currency').default('MYR'),
    version_duration: varchar('version_duration'),
    version_durationMinutes: numeric('version_duration_minutes', { mode: 'number' }),
    version_location: varchar('version_location'),
    version_meetingPoint: varchar('version_meeting_point'),
    version_maxParticipants: numeric('version_max_participants', { mode: 'number' }),
    version_minParticipants: numeric('version_min_participants', { mode: 'number' }).default(2),
    version_tailoredAvailable: boolean('version_tailored_available').default(false),
    version_tailoredNotes: varchar('version_tailored_notes'),
    version_heroImage: varchar('version_hero_image'),
    version_bookingUrl: varchar('version_booking_url'),
    version_instantConfirmation: boolean('version_instant_confirmation').default(true),
    version_metaTitle: varchar('version_meta_title'),
    version_metaDescription: varchar('version_meta_description'),
    version_featured: boolean('version_featured').default(false),
    version_popular: boolean('version_popular').default(false),
    version_new: boolean('version_new').default(false),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_status: enum__tours_v_version_status('version_status').default('draft'),
    version_workflowStatus:
      enum__tours_v_version_workflow_status('version_workflow_status').default('draft'),
    version_meta_title: varchar('version_meta_title'),
    version_meta_description: varchar('version_meta_description'),
    version_meta_image: integer('version_meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__tours_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => [
    index('_tours_v_parent_idx').on(columns.parent),
    index('_tours_v_version_version_slug_idx').on(columns.version_slug),
    index('_tours_v_version_meta_version_meta_image_idx').on(columns.version_meta_image),
    index('_tours_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_tours_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_tours_v_version_version__status_idx').on(columns.version__status),
    index('_tours_v_created_at_idx').on(columns.createdAt),
    index('_tours_v_updated_at_idx').on(columns.updatedAt),
    index('_tours_v_latest_idx').on(columns.latest),
    index('_tours_v_autosave_idx').on(columns.autosave),
  ],
)

export const stories = pgTable(
  'stories',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    author: integer('author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    excerpt: varchar('excerpt'),
    content: varchar('content'),
    publishedDate: timestamp('published_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    featuredImage: varchar('featured_image'),
    metaTitle: varchar('meta_title'),
    metaDescription: varchar('meta_description'),
    status: enum_stories_status('status').default('draft'),
    workflowStatus: enum_stories_workflow_status('workflow_status').default('draft'),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    meta_image: integer('meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_stories_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('stories_slug_idx').on(columns.slug),
    index('stories_author_idx').on(columns.author),
    index('stories_meta_meta_image_idx').on(columns.meta_image),
    index('stories_updated_at_idx').on(columns.updatedAt),
    index('stories_created_at_idx').on(columns.createdAt),
    index('stories__status_idx').on(columns._status),
  ],
)

export const _stories_v = pgTable(
  '_stories_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => stories.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_author: integer('version_author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    version_excerpt: varchar('version_excerpt'),
    version_content: varchar('version_content'),
    version_publishedDate: timestamp('version_published_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_featuredImage: varchar('version_featured_image'),
    version_metaTitle: varchar('version_meta_title'),
    version_metaDescription: varchar('version_meta_description'),
    version_status: enum__stories_v_version_status('version_status').default('draft'),
    version_workflowStatus:
      enum__stories_v_version_workflow_status('version_workflow_status').default('draft'),
    version_meta_title: varchar('version_meta_title'),
    version_meta_description: varchar('version_meta_description'),
    version_meta_image: integer('version_meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__stories_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => [
    index('_stories_v_parent_idx').on(columns.parent),
    index('_stories_v_version_version_slug_idx').on(columns.version_slug),
    index('_stories_v_version_version_author_idx').on(columns.version_author),
    index('_stories_v_version_meta_version_meta_image_idx').on(columns.version_meta_image),
    index('_stories_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_stories_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_stories_v_version_version__status_idx').on(columns.version__status),
    index('_stories_v_created_at_idx').on(columns.createdAt),
    index('_stories_v_updated_at_idx').on(columns.updatedAt),
    index('_stories_v_latest_idx').on(columns.latest),
    index('_stories_v_autosave_idx').on(columns.autosave),
  ],
)

export const testimonials = pgTable(
  'testimonials',
  {
    id: serial('id').primaryKey(),
    author_name: varchar('author_name'),
    author_location: varchar('author_location'),
    rating: numeric('rating', { mode: 'number' }),
    review_text: varchar('review_text'),
    review_title: varchar('review_title'),
    author_photo: varchar('author_photo'),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }),
    visibility_verified: boolean('visibility_verified').default(true),
    visibility_featured: boolean('visibility_featured').default(false),
    platform: varchar('platform'),
    workflowStatus: enum_testimonials_workflow_status('workflow_status').default('draft'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_testimonials_status('_status').default('draft'),
  },
  (columns) => [
    index('testimonials_updated_at_idx').on(columns.updatedAt),
    index('testimonials_created_at_idx').on(columns.createdAt),
    index('testimonials__status_idx').on(columns._status),
  ],
)

export const _testimonials_v = pgTable(
  '_testimonials_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => testimonials.id, {
      onDelete: 'set null',
    }),
    version_author_name: varchar('version_author_name'),
    version_author_location: varchar('version_author_location'),
    version_rating: numeric('version_rating', { mode: 'number' }),
    version_review_text: varchar('version_review_text'),
    version_review_title: varchar('version_review_title'),
    version_author_photo: varchar('version_author_photo'),
    version_date: timestamp('version_date', { mode: 'string', withTimezone: true, precision: 3 }),
    version_visibility_verified: boolean('version_visibility_verified').default(true),
    version_visibility_featured: boolean('version_visibility_featured').default(false),
    version_platform: varchar('version_platform'),
    version_workflowStatus:
      enum__testimonials_v_version_workflow_status('version_workflow_status').default('draft'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__testimonials_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => [
    index('_testimonials_v_parent_idx').on(columns.parent),
    index('_testimonials_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_testimonials_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_testimonials_v_version_version__status_idx').on(columns.version__status),
    index('_testimonials_v_created_at_idx').on(columns.createdAt),
    index('_testimonials_v_updated_at_idx').on(columns.updatedAt),
    index('_testimonials_v_latest_idx').on(columns.latest),
    index('_testimonials_v_autosave_idx').on(columns.autosave),
  ],
)

export const faqs = pgTable(
  'faqs',
  {
    id: serial('id').primaryKey(),
    question: varchar('question'),
    answer: varchar('answer'),
    category: varchar('category'),
    sort_order: numeric('sort_order', { mode: 'number' }),
    tags: varchar('tags'),
    page_visibility: varchar('page_visibility'),
    tour_id: numeric('tour_id', { mode: 'number' }),
    workflowStatus: enum_faqs_workflow_status('workflow_status').default('draft'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_faqs_status('_status').default('draft'),
  },
  (columns) => [
    index('faqs_updated_at_idx').on(columns.updatedAt),
    index('faqs_created_at_idx').on(columns.createdAt),
    index('faqs__status_idx').on(columns._status),
  ],
)

export const _faqs_v = pgTable(
  '_faqs_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => faqs.id, {
      onDelete: 'set null',
    }),
    version_question: varchar('version_question'),
    version_answer: varchar('version_answer'),
    version_category: varchar('version_category'),
    version_sort_order: numeric('version_sort_order', { mode: 'number' }),
    version_tags: varchar('version_tags'),
    version_page_visibility: varchar('version_page_visibility'),
    version_tour_id: numeric('version_tour_id', { mode: 'number' }),
    version_workflowStatus:
      enum__faqs_v_version_workflow_status('version_workflow_status').default('draft'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__faqs_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => [
    index('_faqs_v_parent_idx').on(columns.parent),
    index('_faqs_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_faqs_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_faqs_v_version_version__status_idx').on(columns.version__status),
    index('_faqs_v_created_at_idx').on(columns.createdAt),
    index('_faqs_v_updated_at_idx').on(columns.updatedAt),
    index('_faqs_v_latest_idx').on(columns.latest),
    index('_faqs_v_autosave_idx').on(columns.autosave),
  ],
)

export const media_coverage = pgTable(
  'media_coverage',
  {
    id: serial('id').primaryKey(),
    category: varchar('category'),
    outlet: varchar('outlet').notNull(),
    year: varchar('year'),
    detail: varchar('detail'),
    url: varchar('url'),
    label: varchar('label'),
    logo_domain: varchar('logo_domain'),
    highlight: varchar('highlight'),
    status: enum_media_coverage_status('status').default('draft'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('media_coverage_updated_at_idx').on(columns.updatedAt),
    index('media_coverage_created_at_idx').on(columns.createdAt),
  ],
)

export const dietary_landing_pages = pgTable(
  'dietary_landing_pages',
  {
    id: serial('id').primaryKey(),
    dietary_name: varchar('dietary_name').notNull(),
    slug: varchar('slug').notNull(),
    status: enum_dietary_landing_pages_status('status').default('draft'),
    icon: varchar('icon'),
    color: varchar('color'),
    hero_title: varchar('hero_title'),
    hero_subtitle: varchar('hero_subtitle'),
    hero_description: varchar('hero_description'),
    hero_image: varchar('hero_image'),
    challenges_title: varchar('challenges_title'),
    challenges_content: varchar('challenges_content'),
    options_title: varchar('options_title'),
    options_content: varchar('options_content'),
    tips_content: varchar('tips_content'),
    safe_dishes: jsonb('safe_dishes'),
    dishes_to_avoid: jsonb('dishes_to_avoid'),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    published_at: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    meta_image: integer('meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('dietary_landing_pages_slug_idx').on(columns.slug),
    index('dietary_landing_pages_meta_meta_image_idx').on(columns.meta_image),
    index('dietary_landing_pages_updated_at_idx').on(columns.updatedAt),
    index('dietary_landing_pages_created_at_idx').on(columns.createdAt),
  ],
)

export const specialty_landing_pages = pgTable(
  'specialty_landing_pages',
  {
    id: serial('id').primaryKey(),
    specialty_name: varchar('specialty_name').notNull(),
    slug: varchar('slug').notNull(),
    status: enum_specialty_landing_pages_status('status').default('draft'),
    icon: varchar('icon'),
    color: varchar('color'),
    hero_title: varchar('hero_title'),
    hero_subtitle: varchar('hero_subtitle'),
    hero_description: varchar('hero_description'),
    hero_image: varchar('hero_image'),
    experience_title: varchar('experience_title'),
    experience_content: varchar('experience_content'),
    what_makes_special: varchar('what_makes_special'),
    highlights: jsonb('highlights'),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    published_at: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    meta_image: integer('meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('specialty_landing_pages_slug_idx').on(columns.slug),
    index('specialty_landing_pages_meta_meta_image_idx').on(columns.meta_image),
    index('specialty_landing_pages_updated_at_idx').on(columns.updatedAt),
    index('specialty_landing_pages_created_at_idx').on(columns.createdAt),
  ],
)

export const travel_type_landing_pages = pgTable(
  'travel_type_landing_pages',
  {
    id: serial('id').primaryKey(),
    travel_type_name: varchar('travel_type_name').notNull(),
    slug: varchar('slug').notNull(),
    status: enum_travel_type_landing_pages_status('status').default('draft'),
    icon: varchar('icon'),
    color: varchar('color'),
    hero_title: varchar('hero_title'),
    hero_subtitle: varchar('hero_subtitle'),
    hero_description: varchar('hero_description'),
    hero_image: varchar('hero_image'),
    why_perfect_title: varchar('why_perfect_title'),
    why_perfect_content: varchar('why_perfect_content'),
    what_to_expect: varchar('what_to_expect'),
    tips_content: varchar('tips_content'),
    suitable_tours: jsonb('suitable_tours'),
    key_features: jsonb('key_features'),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    published_at: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    meta_image: integer('meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('travel_type_landing_pages_slug_idx').on(columns.slug),
    index('travel_type_landing_pages_meta_meta_image_idx').on(columns.meta_image),
    index('travel_type_landing_pages_updated_at_idx').on(columns.updatedAt),
    index('travel_type_landing_pages_created_at_idx').on(columns.createdAt),
  ],
)

export const location_landing_pages = pgTable(
  'location_landing_pages',
  {
    id: serial('id').primaryKey(),
    status: enum_location_landing_pages_status('status').default('draft'),
    location_name: varchar('location_name').notNull(),
    slug: varchar('slug').notNull(),
    hero_title: varchar('hero_title'),
    hero_subtitle: varchar('hero_subtitle'),
    hero_description: varchar('hero_description'),
    hero_image: varchar('hero_image'),
    intro_title: varchar('intro_title'),
    intro_content: varchar('intro_content'),
    intro_image: varchar('intro_image'),
    best_time_to_visit: varchar('best_time_to_visit'),
    getting_around: varchar('getting_around'),
    what_to_pack: varchar('what_to_pack'),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    published_at: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    meta_image: integer('meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('location_landing_pages_slug_idx').on(columns.slug),
    index('location_landing_pages_meta_meta_image_idx').on(columns.meta_image),
    index('location_landing_pages_updated_at_idx').on(columns.updatedAt),
    index('location_landing_pages_created_at_idx').on(columns.createdAt),
  ],
)

export const about_page_breadcrumbs = pgTable(
  'about_page_breadcrumbs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    doc: integer('doc_id').references(() => about_page.id, {
      onDelete: 'set null',
    }),
    url: varchar('url'),
    label: varchar('label'),
  },
  (columns) => [
    index('about_page_breadcrumbs_order_idx').on(columns._order),
    index('about_page_breadcrumbs_parent_id_idx').on(columns._parentID),
    index('about_page_breadcrumbs_doc_idx').on(columns.doc),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [about_page.id],
      name: 'about_page_breadcrumbs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const about_page = pgTable(
  'about_page',
  {
    id: serial('id').primaryKey(),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    hero_title: varchar('hero_title'),
    hero_subtitle: varchar('hero_subtitle'),
    founder_story_title: varchar('founder_story_title'),
    founder_story_text: jsonb('founder_story_text'),
    stats: jsonb('stats'),
    timeline: jsonb('timeline'),
    philosophy: varchar('philosophy'),
    team: jsonb('team'),
    parent: integer('parent_id').references((): AnyPgColumn => about_page.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('about_page_parent_idx').on(columns.parent),
    index('about_page_updated_at_idx').on(columns.updatedAt),
    index('about_page_created_at_idx').on(columns.createdAt),
  ],
)

export const contact_page_breadcrumbs = pgTable(
  'contact_page_breadcrumbs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    doc: integer('doc_id').references(() => contact_page.id, {
      onDelete: 'set null',
    }),
    url: varchar('url'),
    label: varchar('label'),
  },
  (columns) => [
    index('contact_page_breadcrumbs_order_idx').on(columns._order),
    index('contact_page_breadcrumbs_parent_id_idx').on(columns._parentID),
    index('contact_page_breadcrumbs_doc_idx').on(columns.doc),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [contact_page.id],
      name: 'contact_page_breadcrumbs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const contact_page = pgTable(
  'contact_page',
  {
    id: serial('id').primaryKey(),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    hero_title: varchar('hero_title'),
    hero_subtitle: varchar('hero_subtitle'),
    contact_intro: varchar('contact_intro'),
    email: varchar('email'),
    phone: varchar('phone'),
    whatsapp: varchar('whatsapp'),
    social_media: jsonb('social_media'),
    faq_section: varchar('faq_section'),
    parent: integer('parent_id').references((): AnyPgColumn => contact_page.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('contact_page_parent_idx').on(columns.parent),
    index('contact_page_updated_at_idx').on(columns.updatedAt),
    index('contact_page_created_at_idx').on(columns.createdAt),
  ],
)

export const thank_you_pages_next_steps = pgTable(
  'thank_you_pages_next_steps',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    step: varchar('step').notNull(),
  },
  (columns) => [
    index('thank_you_pages_next_steps_order_idx').on(columns._order),
    index('thank_you_pages_next_steps_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [thank_you_pages.id],
      name: 'thank_you_pages_next_steps_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const thank_you_pages_cta_section_cta_buttons = pgTable(
  'thank_you_pages_cta_section_cta_buttons',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    text: varchar('text').notNull(),
    url: varchar('url').notNull(),
    variant: enum_thank_you_pages_cta_section_cta_buttons_variant('variant').default('primary'),
  },
  (columns) => [
    index('thank_you_pages_cta_section_cta_buttons_order_idx').on(columns._order),
    index('thank_you_pages_cta_section_cta_buttons_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [thank_you_pages.id],
      name: 'thank_you_pages_cta_section_cta_buttons_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const thank_you_pages = pgTable(
  'thank_you_pages',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    type: enum_thank_you_pages_type('type').notNull(),
    slug: varchar('slug').notNull(),
    status: enum_thank_you_pages_status('status').default('draft'),
    heroSection_heading: varchar('hero_section_heading').default('Thank You!'),
    heroSection_subheading: varchar('hero_section_subheading').default(
      "We've received your message",
    ),
    heroSection_icon: varchar('hero_section_icon').default('✅'),
    message: jsonb('message'),
    contactInfo_showContact: boolean('contact_info_show_contact').default(true),
    contactInfo_email: varchar('contact_info_email'),
    contactInfo_phone: varchar('contact_info_phone'),
    contactInfo_responseTime: varchar('contact_info_response_time').default(
      "We'll respond within 24 hours",
    ),
    ctaSection_showCta: boolean('cta_section_show_cta').default(true),
    seo_metaTitle: varchar('seo_meta_title'),
    seo_metaDescription: varchar('seo_meta_description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('thank_you_pages_slug_idx').on(columns.slug),
    index('thank_you_pages_updated_at_idx').on(columns.updatedAt),
    index('thank_you_pages_created_at_idx').on(columns.createdAt),
  ],
)

export const translations = pgTable(
  'translations',
  {
    id: serial('id').primaryKey(),
    label: varchar('label').notNull(),
    locale: enum_translations_locale('locale').notNull(),
    collection: enum_translations_collection('collection').notNull(),
    status: enum_translations_status('status').default('draft'),
    translator: varchar('translator'),
    translatedAt: timestamp('translated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    fields_name: varchar('fields_name'),
    fields_tagline: varchar('fields_tagline'),
    fields_shortDescription: varchar('fields_short_description'),
    fields_fullDescription: varchar('fields_full_description'),
    fields_content: varchar('fields_content'),
    fields_excerpt: varchar('fields_excerpt'),
    fields_question: varchar('fields_question'),
    fields_answer: varchar('fields_answer'),
    fields_reviewText: varchar('fields_review_text'),
    fields_reviewTitle: varchar('fields_review_title'),
    fields_heroTitle: varchar('fields_hero_title'),
    fields_heroSubtitle: varchar('fields_hero_subtitle'),
    fields_heroDescription: varchar('fields_hero_description'),
    seo_metaTitle: varchar('seo_meta_title'),
    seo_metaDescription: varchar('seo_meta_description'),
    notes: varchar('notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('translations_updated_at_idx').on(columns.updatedAt),
    index('translations_created_at_idx').on(columns.createdAt),
  ],
)

export const translations_rels = pgTable(
  'translations_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    toursID: integer('tours_id'),
    storiesID: integer('stories_id'),
    testimonialsID: integer('testimonials_id'),
    faqsID: integer('faqs_id'),
    media_coverageID: integer('media_coverage_id'),
    dietary_landing_pagesID: integer('dietary_landing_pages_id'),
    specialty_landing_pagesID: integer('specialty_landing_pages_id'),
    travel_type_landing_pagesID: integer('travel_type_landing_pages_id'),
    location_landing_pagesID: integer('location_landing_pages_id'),
  },
  (columns) => [
    index('translations_rels_order_idx').on(columns.order),
    index('translations_rels_parent_idx').on(columns.parent),
    index('translations_rels_path_idx').on(columns.path),
    index('translations_rels_tours_id_idx').on(columns.toursID),
    index('translations_rels_stories_id_idx').on(columns.storiesID),
    index('translations_rels_testimonials_id_idx').on(columns.testimonialsID),
    index('translations_rels_faqs_id_idx').on(columns.faqsID),
    index('translations_rels_media_coverage_id_idx').on(columns.media_coverageID),
    index('translations_rels_dietary_landing_pages_id_idx').on(columns.dietary_landing_pagesID),
    index('translations_rels_specialty_landing_pages_id_idx').on(columns.specialty_landing_pagesID),
    index('translations_rels_travel_type_landing_pages_id_idx').on(
      columns.travel_type_landing_pagesID,
    ),
    index('translations_rels_location_landing_pages_id_idx').on(columns.location_landing_pagesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [translations.id],
      name: 'translations_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['toursID']],
      foreignColumns: [tours.id],
      name: 'translations_rels_tours_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['storiesID']],
      foreignColumns: [stories.id],
      name: 'translations_rels_stories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['testimonialsID']],
      foreignColumns: [testimonials.id],
      name: 'translations_rels_testimonials_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['faqsID']],
      foreignColumns: [faqs.id],
      name: 'translations_rels_faqs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['media_coverageID']],
      foreignColumns: [media_coverage.id],
      name: 'translations_rels_media_coverage_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['dietary_landing_pagesID']],
      foreignColumns: [dietary_landing_pages.id],
      name: 'translations_rels_dietary_landing_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['specialty_landing_pagesID']],
      foreignColumns: [specialty_landing_pages.id],
      name: 'translations_rels_specialty_landing_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['travel_type_landing_pagesID']],
      foreignColumns: [travel_type_landing_pages.id],
      name: 'translations_rels_travel_type_landing_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['location_landing_pagesID']],
      foreignColumns: [location_landing_pages.id],
      name: 'translations_rels_location_landing_pages_fk',
    }).onDelete('cascade'),
  ],
)

export const site_settings = pgTable(
  'site_settings',
  {
    id: serial('id').primaryKey(),
    site_name: varchar('site_name'),
    tagline: varchar('tagline'),
    description: varchar('description'),
    hero_title: varchar('hero_title'),
    hero_subtitle: varchar('hero_subtitle'),
    hero_description: varchar('hero_description'),
    hero_image: varchar('hero_image'),
    booking_url: varchar('booking_url'),
    social_media: jsonb('social_media'),
    contact_email: varchar('contact_email'),
    contact_phone: varchar('contact_phone'),
    whatsapp_number: varchar('whatsapp_number'),
    address: varchar('address'),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('site_settings_updated_at_idx').on(columns.updatedAt),
    index('site_settings_created_at_idx').on(columns.createdAt),
  ],
)

export const redirects = pgTable(
  'redirects',
  {
    id: serial('id').primaryKey(),
    from: varchar('from').notNull(),
    to_type: enum_redirects_to_type('to_type').default('reference'),
    to_url: varchar('to_url'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('redirects_from_idx').on(columns.from),
    index('redirects_updated_at_idx').on(columns.updatedAt),
    index('redirects_created_at_idx').on(columns.createdAt),
  ],
)

export const redirects_rels = pgTable(
  'redirects_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    toursID: integer('tours_id'),
    storiesID: integer('stories_id'),
    dietary_landing_pagesID: integer('dietary_landing_pages_id'),
    specialty_landing_pagesID: integer('specialty_landing_pages_id'),
    travel_type_landing_pagesID: integer('travel_type_landing_pages_id'),
    location_landing_pagesID: integer('location_landing_pages_id'),
  },
  (columns) => [
    index('redirects_rels_order_idx').on(columns.order),
    index('redirects_rels_parent_idx').on(columns.parent),
    index('redirects_rels_path_idx').on(columns.path),
    index('redirects_rels_tours_id_idx').on(columns.toursID),
    index('redirects_rels_stories_id_idx').on(columns.storiesID),
    index('redirects_rels_dietary_landing_pages_id_idx').on(columns.dietary_landing_pagesID),
    index('redirects_rels_specialty_landing_pages_id_idx').on(columns.specialty_landing_pagesID),
    index('redirects_rels_travel_type_landing_pages_id_idx').on(
      columns.travel_type_landing_pagesID,
    ),
    index('redirects_rels_location_landing_pages_id_idx').on(columns.location_landing_pagesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [redirects.id],
      name: 'redirects_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['toursID']],
      foreignColumns: [tours.id],
      name: 'redirects_rels_tours_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['storiesID']],
      foreignColumns: [stories.id],
      name: 'redirects_rels_stories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['dietary_landing_pagesID']],
      foreignColumns: [dietary_landing_pages.id],
      name: 'redirects_rels_dietary_landing_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['specialty_landing_pagesID']],
      foreignColumns: [specialty_landing_pages.id],
      name: 'redirects_rels_specialty_landing_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['travel_type_landing_pagesID']],
      foreignColumns: [travel_type_landing_pages.id],
      name: 'redirects_rels_travel_type_landing_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['location_landing_pagesID']],
      foreignColumns: [location_landing_pages.id],
      name: 'redirects_rels_location_landing_pages_fk',
    }).onDelete('cascade'),
  ],
)

export const search = pgTable(
  'search',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    priority: numeric('priority', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('search_updated_at_idx').on(columns.updatedAt),
    index('search_created_at_idx').on(columns.createdAt),
  ],
)

export const search_rels = pgTable(
  'search_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    toursID: integer('tours_id'),
    storiesID: integer('stories_id'),
    faqsID: integer('faqs_id'),
    testimonialsID: integer('testimonials_id'),
  },
  (columns) => [
    index('search_rels_order_idx').on(columns.order),
    index('search_rels_parent_idx').on(columns.parent),
    index('search_rels_path_idx').on(columns.path),
    index('search_rels_tours_id_idx').on(columns.toursID),
    index('search_rels_stories_id_idx').on(columns.storiesID),
    index('search_rels_faqs_id_idx').on(columns.faqsID),
    index('search_rels_testimonials_id_idx').on(columns.testimonialsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [search.id],
      name: 'search_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['toursID']],
      foreignColumns: [tours.id],
      name: 'search_rels_tours_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['storiesID']],
      foreignColumns: [stories.id],
      name: 'search_rels_stories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['faqsID']],
      foreignColumns: [faqs.id],
      name: 'search_rels_faqs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['testimonialsID']],
      foreignColumns: [testimonials.id],
      name: 'search_rels_testimonials_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    toursID: integer('tours_id'),
    storiesID: integer('stories_id'),
    testimonialsID: integer('testimonials_id'),
    faqsID: integer('faqs_id'),
    media_coverageID: integer('media_coverage_id'),
    dietary_landing_pagesID: integer('dietary_landing_pages_id'),
    specialty_landing_pagesID: integer('specialty_landing_pages_id'),
    travel_type_landing_pagesID: integer('travel_type_landing_pages_id'),
    location_landing_pagesID: integer('location_landing_pages_id'),
    about_pageID: integer('about_page_id'),
    contact_pageID: integer('contact_page_id'),
    thank_you_pagesID: integer('thank_you_pages_id'),
    translationsID: integer('translations_id'),
    site_settingsID: integer('site_settings_id'),
    redirectsID: integer('redirects_id'),
    searchID: integer('search_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_tours_id_idx').on(columns.toursID),
    index('payload_locked_documents_rels_stories_id_idx').on(columns.storiesID),
    index('payload_locked_documents_rels_testimonials_id_idx').on(columns.testimonialsID),
    index('payload_locked_documents_rels_faqs_id_idx').on(columns.faqsID),
    index('payload_locked_documents_rels_media_coverage_id_idx').on(columns.media_coverageID),
    index('payload_locked_documents_rels_dietary_landing_pages_id_idx').on(
      columns.dietary_landing_pagesID,
    ),
    index('payload_locked_documents_rels_specialty_landing_pages_id_idx').on(
      columns.specialty_landing_pagesID,
    ),
    index('payload_locked_documents_rels_travel_type_landing_pages__idx').on(
      columns.travel_type_landing_pagesID,
    ),
    index('payload_locked_documents_rels_location_landing_pages_id_idx').on(
      columns.location_landing_pagesID,
    ),
    index('payload_locked_documents_rels_about_page_id_idx').on(columns.about_pageID),
    index('payload_locked_documents_rels_contact_page_id_idx').on(columns.contact_pageID),
    index('payload_locked_documents_rels_thank_you_pages_id_idx').on(columns.thank_you_pagesID),
    index('payload_locked_documents_rels_translations_id_idx').on(columns.translationsID),
    index('payload_locked_documents_rels_site_settings_id_idx').on(columns.site_settingsID),
    index('payload_locked_documents_rels_redirects_id_idx').on(columns.redirectsID),
    index('payload_locked_documents_rels_search_id_idx').on(columns.searchID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['toursID']],
      foreignColumns: [tours.id],
      name: 'payload_locked_documents_rels_tours_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['storiesID']],
      foreignColumns: [stories.id],
      name: 'payload_locked_documents_rels_stories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['testimonialsID']],
      foreignColumns: [testimonials.id],
      name: 'payload_locked_documents_rels_testimonials_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['faqsID']],
      foreignColumns: [faqs.id],
      name: 'payload_locked_documents_rels_faqs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['media_coverageID']],
      foreignColumns: [media_coverage.id],
      name: 'payload_locked_documents_rels_media_coverage_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['dietary_landing_pagesID']],
      foreignColumns: [dietary_landing_pages.id],
      name: 'payload_locked_documents_rels_dietary_landing_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['specialty_landing_pagesID']],
      foreignColumns: [specialty_landing_pages.id],
      name: 'payload_locked_documents_rels_specialty_landing_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['travel_type_landing_pagesID']],
      foreignColumns: [travel_type_landing_pages.id],
      name: 'payload_locked_documents_rels_travel_type_landing_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['location_landing_pagesID']],
      foreignColumns: [location_landing_pages.id],
      name: 'payload_locked_documents_rels_location_landing_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['about_pageID']],
      foreignColumns: [about_page.id],
      name: 'payload_locked_documents_rels_about_page_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['contact_pageID']],
      foreignColumns: [contact_page.id],
      name: 'payload_locked_documents_rels_contact_page_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['thank_you_pagesID']],
      foreignColumns: [thank_you_pages.id],
      name: 'payload_locked_documents_rels_thank_you_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['translationsID']],
      foreignColumns: [translations.id],
      name: 'payload_locked_documents_rels_translations_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['site_settingsID']],
      foreignColumns: [site_settings.id],
      name: 'payload_locked_documents_rels_site_settings_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['redirectsID']],
      foreignColumns: [redirects.id],
      name: 'payload_locked_documents_rels_redirects_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['searchID']],
      foreignColumns: [search.id],
      name: 'payload_locked_documents_rels_search_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_tours_dietary_options = relations(tours_dietary_options, ({ one }) => ({
  _parentID: one(tours, {
    fields: [tours_dietary_options._parentID],
    references: [tours.id],
    relationName: 'dietaryOptions',
  }),
}))
export const relations_tours_travel_types = relations(tours_travel_types, ({ one }) => ({
  _parentID: one(tours, {
    fields: [tours_travel_types._parentID],
    references: [tours.id],
    relationName: 'travelTypes',
  }),
}))
export const relations_tours_specialty_experiences = relations(
  tours_specialty_experiences,
  ({ one }) => ({
    _parentID: one(tours, {
      fields: [tours_specialty_experiences._parentID],
      references: [tours.id],
      relationName: 'specialtyExperiences',
    }),
  }),
)
export const relations_tours_gallery_images = relations(tours_gallery_images, ({ one }) => ({
  _parentID: one(tours, {
    fields: [tours_gallery_images._parentID],
    references: [tours.id],
    relationName: 'galleryImages',
  }),
}))
export const relations_tours_whats_included = relations(tours_whats_included, ({ one }) => ({
  _parentID: one(tours, {
    fields: [tours_whats_included._parentID],
    references: [tours.id],
    relationName: 'whatsIncluded',
  }),
}))
export const relations_tours_whats_excluded = relations(tours_whats_excluded, ({ one }) => ({
  _parentID: one(tours, {
    fields: [tours_whats_excluded._parentID],
    references: [tours.id],
    relationName: 'whatsExcluded',
  }),
}))
export const relations_tours_highlights = relations(tours_highlights, ({ one }) => ({
  _parentID: one(tours, {
    fields: [tours_highlights._parentID],
    references: [tours.id],
    relationName: 'highlights',
  }),
}))
export const relations_tours = relations(tours, ({ one, many }) => ({
  dietaryOptions: many(tours_dietary_options, {
    relationName: 'dietaryOptions',
  }),
  travelTypes: many(tours_travel_types, {
    relationName: 'travelTypes',
  }),
  specialtyExperiences: many(tours_specialty_experiences, {
    relationName: 'specialtyExperiences',
  }),
  galleryImages: many(tours_gallery_images, {
    relationName: 'galleryImages',
  }),
  whatsIncluded: many(tours_whats_included, {
    relationName: 'whatsIncluded',
  }),
  whatsExcluded: many(tours_whats_excluded, {
    relationName: 'whatsExcluded',
  }),
  highlights: many(tours_highlights, {
    relationName: 'highlights',
  }),
  meta_image: one(media, {
    fields: [tours.meta_image],
    references: [media.id],
    relationName: 'meta_image',
  }),
}))
export const relations__tours_v_version_dietary_options = relations(
  _tours_v_version_dietary_options,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_dietary_options._parentID],
      references: [_tours_v.id],
      relationName: 'version_dietaryOptions',
    }),
  }),
)
export const relations__tours_v_version_travel_types = relations(
  _tours_v_version_travel_types,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_travel_types._parentID],
      references: [_tours_v.id],
      relationName: 'version_travelTypes',
    }),
  }),
)
export const relations__tours_v_version_specialty_experiences = relations(
  _tours_v_version_specialty_experiences,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_specialty_experiences._parentID],
      references: [_tours_v.id],
      relationName: 'version_specialtyExperiences',
    }),
  }),
)
export const relations__tours_v_version_gallery_images = relations(
  _tours_v_version_gallery_images,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_gallery_images._parentID],
      references: [_tours_v.id],
      relationName: 'version_galleryImages',
    }),
  }),
)
export const relations__tours_v_version_whats_included = relations(
  _tours_v_version_whats_included,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_whats_included._parentID],
      references: [_tours_v.id],
      relationName: 'version_whatsIncluded',
    }),
  }),
)
export const relations__tours_v_version_whats_excluded = relations(
  _tours_v_version_whats_excluded,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_whats_excluded._parentID],
      references: [_tours_v.id],
      relationName: 'version_whatsExcluded',
    }),
  }),
)
export const relations__tours_v_version_highlights = relations(
  _tours_v_version_highlights,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_highlights._parentID],
      references: [_tours_v.id],
      relationName: 'version_highlights',
    }),
  }),
)
export const relations__tours_v = relations(_tours_v, ({ one, many }) => ({
  parent: one(tours, {
    fields: [_tours_v.parent],
    references: [tours.id],
    relationName: 'parent',
  }),
  version_dietaryOptions: many(_tours_v_version_dietary_options, {
    relationName: 'version_dietaryOptions',
  }),
  version_travelTypes: many(_tours_v_version_travel_types, {
    relationName: 'version_travelTypes',
  }),
  version_specialtyExperiences: many(_tours_v_version_specialty_experiences, {
    relationName: 'version_specialtyExperiences',
  }),
  version_galleryImages: many(_tours_v_version_gallery_images, {
    relationName: 'version_galleryImages',
  }),
  version_whatsIncluded: many(_tours_v_version_whats_included, {
    relationName: 'version_whatsIncluded',
  }),
  version_whatsExcluded: many(_tours_v_version_whats_excluded, {
    relationName: 'version_whatsExcluded',
  }),
  version_highlights: many(_tours_v_version_highlights, {
    relationName: 'version_highlights',
  }),
  version_meta_image: one(media, {
    fields: [_tours_v.version_meta_image],
    references: [media.id],
    relationName: 'version_meta_image',
  }),
}))
export const relations_stories = relations(stories, ({ one }) => ({
  author: one(users, {
    fields: [stories.author],
    references: [users.id],
    relationName: 'author',
  }),
  meta_image: one(media, {
    fields: [stories.meta_image],
    references: [media.id],
    relationName: 'meta_image',
  }),
}))
export const relations__stories_v = relations(_stories_v, ({ one }) => ({
  parent: one(stories, {
    fields: [_stories_v.parent],
    references: [stories.id],
    relationName: 'parent',
  }),
  version_author: one(users, {
    fields: [_stories_v.version_author],
    references: [users.id],
    relationName: 'version_author',
  }),
  version_meta_image: one(media, {
    fields: [_stories_v.version_meta_image],
    references: [media.id],
    relationName: 'version_meta_image',
  }),
}))
export const relations_testimonials = relations(testimonials, () => ({}))
export const relations__testimonials_v = relations(_testimonials_v, ({ one }) => ({
  parent: one(testimonials, {
    fields: [_testimonials_v.parent],
    references: [testimonials.id],
    relationName: 'parent',
  }),
}))
export const relations_faqs = relations(faqs, () => ({}))
export const relations__faqs_v = relations(_faqs_v, ({ one }) => ({
  parent: one(faqs, {
    fields: [_faqs_v.parent],
    references: [faqs.id],
    relationName: 'parent',
  }),
}))
export const relations_media_coverage = relations(media_coverage, () => ({}))
export const relations_dietary_landing_pages = relations(dietary_landing_pages, ({ one }) => ({
  meta_image: one(media, {
    fields: [dietary_landing_pages.meta_image],
    references: [media.id],
    relationName: 'meta_image',
  }),
}))
export const relations_specialty_landing_pages = relations(specialty_landing_pages, ({ one }) => ({
  meta_image: one(media, {
    fields: [specialty_landing_pages.meta_image],
    references: [media.id],
    relationName: 'meta_image',
  }),
}))
export const relations_travel_type_landing_pages = relations(
  travel_type_landing_pages,
  ({ one }) => ({
    meta_image: one(media, {
      fields: [travel_type_landing_pages.meta_image],
      references: [media.id],
      relationName: 'meta_image',
    }),
  }),
)
export const relations_location_landing_pages = relations(location_landing_pages, ({ one }) => ({
  meta_image: one(media, {
    fields: [location_landing_pages.meta_image],
    references: [media.id],
    relationName: 'meta_image',
  }),
}))
export const relations_about_page_breadcrumbs = relations(about_page_breadcrumbs, ({ one }) => ({
  _parentID: one(about_page, {
    fields: [about_page_breadcrumbs._parentID],
    references: [about_page.id],
    relationName: 'breadcrumbs',
  }),
  doc: one(about_page, {
    fields: [about_page_breadcrumbs.doc],
    references: [about_page.id],
    relationName: 'doc',
  }),
}))
export const relations_about_page = relations(about_page, ({ one, many }) => ({
  parent: one(about_page, {
    fields: [about_page.parent],
    references: [about_page.id],
    relationName: 'parent',
  }),
  breadcrumbs: many(about_page_breadcrumbs, {
    relationName: 'breadcrumbs',
  }),
}))
export const relations_contact_page_breadcrumbs = relations(
  contact_page_breadcrumbs,
  ({ one }) => ({
    _parentID: one(contact_page, {
      fields: [contact_page_breadcrumbs._parentID],
      references: [contact_page.id],
      relationName: 'breadcrumbs',
    }),
    doc: one(contact_page, {
      fields: [contact_page_breadcrumbs.doc],
      references: [contact_page.id],
      relationName: 'doc',
    }),
  }),
)
export const relations_contact_page = relations(contact_page, ({ one, many }) => ({
  parent: one(contact_page, {
    fields: [contact_page.parent],
    references: [contact_page.id],
    relationName: 'parent',
  }),
  breadcrumbs: many(contact_page_breadcrumbs, {
    relationName: 'breadcrumbs',
  }),
}))
export const relations_thank_you_pages_next_steps = relations(
  thank_you_pages_next_steps,
  ({ one }) => ({
    _parentID: one(thank_you_pages, {
      fields: [thank_you_pages_next_steps._parentID],
      references: [thank_you_pages.id],
      relationName: 'nextSteps',
    }),
  }),
)
export const relations_thank_you_pages_cta_section_cta_buttons = relations(
  thank_you_pages_cta_section_cta_buttons,
  ({ one }) => ({
    _parentID: one(thank_you_pages, {
      fields: [thank_you_pages_cta_section_cta_buttons._parentID],
      references: [thank_you_pages.id],
      relationName: 'ctaSection_ctaButtons',
    }),
  }),
)
export const relations_thank_you_pages = relations(thank_you_pages, ({ many }) => ({
  nextSteps: many(thank_you_pages_next_steps, {
    relationName: 'nextSteps',
  }),
  ctaSection_ctaButtons: many(thank_you_pages_cta_section_cta_buttons, {
    relationName: 'ctaSection_ctaButtons',
  }),
}))
export const relations_translations_rels = relations(translations_rels, ({ one }) => ({
  parent: one(translations, {
    fields: [translations_rels.parent],
    references: [translations.id],
    relationName: '_rels',
  }),
  toursID: one(tours, {
    fields: [translations_rels.toursID],
    references: [tours.id],
    relationName: 'tours',
  }),
  storiesID: one(stories, {
    fields: [translations_rels.storiesID],
    references: [stories.id],
    relationName: 'stories',
  }),
  testimonialsID: one(testimonials, {
    fields: [translations_rels.testimonialsID],
    references: [testimonials.id],
    relationName: 'testimonials',
  }),
  faqsID: one(faqs, {
    fields: [translations_rels.faqsID],
    references: [faqs.id],
    relationName: 'faqs',
  }),
  media_coverageID: one(media_coverage, {
    fields: [translations_rels.media_coverageID],
    references: [media_coverage.id],
    relationName: 'media_coverage',
  }),
  dietary_landing_pagesID: one(dietary_landing_pages, {
    fields: [translations_rels.dietary_landing_pagesID],
    references: [dietary_landing_pages.id],
    relationName: 'dietary_landing_pages',
  }),
  specialty_landing_pagesID: one(specialty_landing_pages, {
    fields: [translations_rels.specialty_landing_pagesID],
    references: [specialty_landing_pages.id],
    relationName: 'specialty_landing_pages',
  }),
  travel_type_landing_pagesID: one(travel_type_landing_pages, {
    fields: [translations_rels.travel_type_landing_pagesID],
    references: [travel_type_landing_pages.id],
    relationName: 'travel_type_landing_pages',
  }),
  location_landing_pagesID: one(location_landing_pages, {
    fields: [translations_rels.location_landing_pagesID],
    references: [location_landing_pages.id],
    relationName: 'location_landing_pages',
  }),
}))
export const relations_translations = relations(translations, ({ many }) => ({
  _rels: many(translations_rels, {
    relationName: '_rels',
  }),
}))
export const relations_site_settings = relations(site_settings, () => ({}))
export const relations_redirects_rels = relations(redirects_rels, ({ one }) => ({
  parent: one(redirects, {
    fields: [redirects_rels.parent],
    references: [redirects.id],
    relationName: '_rels',
  }),
  toursID: one(tours, {
    fields: [redirects_rels.toursID],
    references: [tours.id],
    relationName: 'tours',
  }),
  storiesID: one(stories, {
    fields: [redirects_rels.storiesID],
    references: [stories.id],
    relationName: 'stories',
  }),
  dietary_landing_pagesID: one(dietary_landing_pages, {
    fields: [redirects_rels.dietary_landing_pagesID],
    references: [dietary_landing_pages.id],
    relationName: 'dietary_landing_pages',
  }),
  specialty_landing_pagesID: one(specialty_landing_pages, {
    fields: [redirects_rels.specialty_landing_pagesID],
    references: [specialty_landing_pages.id],
    relationName: 'specialty_landing_pages',
  }),
  travel_type_landing_pagesID: one(travel_type_landing_pages, {
    fields: [redirects_rels.travel_type_landing_pagesID],
    references: [travel_type_landing_pages.id],
    relationName: 'travel_type_landing_pages',
  }),
  location_landing_pagesID: one(location_landing_pages, {
    fields: [redirects_rels.location_landing_pagesID],
    references: [location_landing_pages.id],
    relationName: 'location_landing_pages',
  }),
}))
export const relations_redirects = relations(redirects, ({ many }) => ({
  _rels: many(redirects_rels, {
    relationName: '_rels',
  }),
}))
export const relations_search_rels = relations(search_rels, ({ one }) => ({
  parent: one(search, {
    fields: [search_rels.parent],
    references: [search.id],
    relationName: '_rels',
  }),
  toursID: one(tours, {
    fields: [search_rels.toursID],
    references: [tours.id],
    relationName: 'tours',
  }),
  storiesID: one(stories, {
    fields: [search_rels.storiesID],
    references: [stories.id],
    relationName: 'stories',
  }),
  faqsID: one(faqs, {
    fields: [search_rels.faqsID],
    references: [faqs.id],
    relationName: 'faqs',
  }),
  testimonialsID: one(testimonials, {
    fields: [search_rels.testimonialsID],
    references: [testimonials.id],
    relationName: 'testimonials',
  }),
}))
export const relations_search = relations(search, ({ many }) => ({
  _rels: many(search_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    toursID: one(tours, {
      fields: [payload_locked_documents_rels.toursID],
      references: [tours.id],
      relationName: 'tours',
    }),
    storiesID: one(stories, {
      fields: [payload_locked_documents_rels.storiesID],
      references: [stories.id],
      relationName: 'stories',
    }),
    testimonialsID: one(testimonials, {
      fields: [payload_locked_documents_rels.testimonialsID],
      references: [testimonials.id],
      relationName: 'testimonials',
    }),
    faqsID: one(faqs, {
      fields: [payload_locked_documents_rels.faqsID],
      references: [faqs.id],
      relationName: 'faqs',
    }),
    media_coverageID: one(media_coverage, {
      fields: [payload_locked_documents_rels.media_coverageID],
      references: [media_coverage.id],
      relationName: 'media_coverage',
    }),
    dietary_landing_pagesID: one(dietary_landing_pages, {
      fields: [payload_locked_documents_rels.dietary_landing_pagesID],
      references: [dietary_landing_pages.id],
      relationName: 'dietary_landing_pages',
    }),
    specialty_landing_pagesID: one(specialty_landing_pages, {
      fields: [payload_locked_documents_rels.specialty_landing_pagesID],
      references: [specialty_landing_pages.id],
      relationName: 'specialty_landing_pages',
    }),
    travel_type_landing_pagesID: one(travel_type_landing_pages, {
      fields: [payload_locked_documents_rels.travel_type_landing_pagesID],
      references: [travel_type_landing_pages.id],
      relationName: 'travel_type_landing_pages',
    }),
    location_landing_pagesID: one(location_landing_pages, {
      fields: [payload_locked_documents_rels.location_landing_pagesID],
      references: [location_landing_pages.id],
      relationName: 'location_landing_pages',
    }),
    about_pageID: one(about_page, {
      fields: [payload_locked_documents_rels.about_pageID],
      references: [about_page.id],
      relationName: 'about_page',
    }),
    contact_pageID: one(contact_page, {
      fields: [payload_locked_documents_rels.contact_pageID],
      references: [contact_page.id],
      relationName: 'contact_page',
    }),
    thank_you_pagesID: one(thank_you_pages, {
      fields: [payload_locked_documents_rels.thank_you_pagesID],
      references: [thank_you_pages.id],
      relationName: 'thank_you_pages',
    }),
    translationsID: one(translations, {
      fields: [payload_locked_documents_rels.translationsID],
      references: [translations.id],
      relationName: 'translations',
    }),
    site_settingsID: one(site_settings, {
      fields: [payload_locked_documents_rels.site_settingsID],
      references: [site_settings.id],
      relationName: 'site_settings',
    }),
    redirectsID: one(redirects, {
      fields: [payload_locked_documents_rels.redirectsID],
      references: [redirects.id],
      relationName: 'redirects',
    }),
    searchID: one(search, {
      fields: [payload_locked_documents_rels.searchID],
      references: [search.id],
      relationName: 'search',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_tours_status: typeof enum_tours_status
  enum_tours_workflow_status: typeof enum_tours_workflow_status
  enum__tours_v_version_status: typeof enum__tours_v_version_status
  enum__tours_v_version_workflow_status: typeof enum__tours_v_version_workflow_status
  enum_stories_status: typeof enum_stories_status
  enum_stories_workflow_status: typeof enum_stories_workflow_status
  enum__stories_v_version_status: typeof enum__stories_v_version_status
  enum__stories_v_version_workflow_status: typeof enum__stories_v_version_workflow_status
  enum_testimonials_workflow_status: typeof enum_testimonials_workflow_status
  enum_testimonials_status: typeof enum_testimonials_status
  enum__testimonials_v_version_workflow_status: typeof enum__testimonials_v_version_workflow_status
  enum__testimonials_v_version_status: typeof enum__testimonials_v_version_status
  enum_faqs_workflow_status: typeof enum_faqs_workflow_status
  enum_faqs_status: typeof enum_faqs_status
  enum__faqs_v_version_workflow_status: typeof enum__faqs_v_version_workflow_status
  enum__faqs_v_version_status: typeof enum__faqs_v_version_status
  enum_media_coverage_status: typeof enum_media_coverage_status
  enum_dietary_landing_pages_status: typeof enum_dietary_landing_pages_status
  enum_specialty_landing_pages_status: typeof enum_specialty_landing_pages_status
  enum_travel_type_landing_pages_status: typeof enum_travel_type_landing_pages_status
  enum_location_landing_pages_status: typeof enum_location_landing_pages_status
  enum_thank_you_pages_cta_section_cta_buttons_variant: typeof enum_thank_you_pages_cta_section_cta_buttons_variant
  enum_thank_you_pages_type: typeof enum_thank_you_pages_type
  enum_thank_you_pages_status: typeof enum_thank_you_pages_status
  enum_translations_locale: typeof enum_translations_locale
  enum_translations_collection: typeof enum_translations_collection
  enum_translations_status: typeof enum_translations_status
  enum_redirects_to_type: typeof enum_redirects_to_type
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  tours_dietary_options: typeof tours_dietary_options
  tours_travel_types: typeof tours_travel_types
  tours_specialty_experiences: typeof tours_specialty_experiences
  tours_gallery_images: typeof tours_gallery_images
  tours_whats_included: typeof tours_whats_included
  tours_whats_excluded: typeof tours_whats_excluded
  tours_highlights: typeof tours_highlights
  tours: typeof tours
  _tours_v_version_dietary_options: typeof _tours_v_version_dietary_options
  _tours_v_version_travel_types: typeof _tours_v_version_travel_types
  _tours_v_version_specialty_experiences: typeof _tours_v_version_specialty_experiences
  _tours_v_version_gallery_images: typeof _tours_v_version_gallery_images
  _tours_v_version_whats_included: typeof _tours_v_version_whats_included
  _tours_v_version_whats_excluded: typeof _tours_v_version_whats_excluded
  _tours_v_version_highlights: typeof _tours_v_version_highlights
  _tours_v: typeof _tours_v
  stories: typeof stories
  _stories_v: typeof _stories_v
  testimonials: typeof testimonials
  _testimonials_v: typeof _testimonials_v
  faqs: typeof faqs
  _faqs_v: typeof _faqs_v
  media_coverage: typeof media_coverage
  dietary_landing_pages: typeof dietary_landing_pages
  specialty_landing_pages: typeof specialty_landing_pages
  travel_type_landing_pages: typeof travel_type_landing_pages
  location_landing_pages: typeof location_landing_pages
  about_page_breadcrumbs: typeof about_page_breadcrumbs
  about_page: typeof about_page
  contact_page_breadcrumbs: typeof contact_page_breadcrumbs
  contact_page: typeof contact_page
  thank_you_pages_next_steps: typeof thank_you_pages_next_steps
  thank_you_pages_cta_section_cta_buttons: typeof thank_you_pages_cta_section_cta_buttons
  thank_you_pages: typeof thank_you_pages
  translations: typeof translations
  translations_rels: typeof translations_rels
  site_settings: typeof site_settings
  redirects: typeof redirects
  redirects_rels: typeof redirects_rels
  search: typeof search
  search_rels: typeof search_rels
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_tours_dietary_options: typeof relations_tours_dietary_options
  relations_tours_travel_types: typeof relations_tours_travel_types
  relations_tours_specialty_experiences: typeof relations_tours_specialty_experiences
  relations_tours_gallery_images: typeof relations_tours_gallery_images
  relations_tours_whats_included: typeof relations_tours_whats_included
  relations_tours_whats_excluded: typeof relations_tours_whats_excluded
  relations_tours_highlights: typeof relations_tours_highlights
  relations_tours: typeof relations_tours
  relations__tours_v_version_dietary_options: typeof relations__tours_v_version_dietary_options
  relations__tours_v_version_travel_types: typeof relations__tours_v_version_travel_types
  relations__tours_v_version_specialty_experiences: typeof relations__tours_v_version_specialty_experiences
  relations__tours_v_version_gallery_images: typeof relations__tours_v_version_gallery_images
  relations__tours_v_version_whats_included: typeof relations__tours_v_version_whats_included
  relations__tours_v_version_whats_excluded: typeof relations__tours_v_version_whats_excluded
  relations__tours_v_version_highlights: typeof relations__tours_v_version_highlights
  relations__tours_v: typeof relations__tours_v
  relations_stories: typeof relations_stories
  relations__stories_v: typeof relations__stories_v
  relations_testimonials: typeof relations_testimonials
  relations__testimonials_v: typeof relations__testimonials_v
  relations_faqs: typeof relations_faqs
  relations__faqs_v: typeof relations__faqs_v
  relations_media_coverage: typeof relations_media_coverage
  relations_dietary_landing_pages: typeof relations_dietary_landing_pages
  relations_specialty_landing_pages: typeof relations_specialty_landing_pages
  relations_travel_type_landing_pages: typeof relations_travel_type_landing_pages
  relations_location_landing_pages: typeof relations_location_landing_pages
  relations_about_page_breadcrumbs: typeof relations_about_page_breadcrumbs
  relations_about_page: typeof relations_about_page
  relations_contact_page_breadcrumbs: typeof relations_contact_page_breadcrumbs
  relations_contact_page: typeof relations_contact_page
  relations_thank_you_pages_next_steps: typeof relations_thank_you_pages_next_steps
  relations_thank_you_pages_cta_section_cta_buttons: typeof relations_thank_you_pages_cta_section_cta_buttons
  relations_thank_you_pages: typeof relations_thank_you_pages
  relations_translations_rels: typeof relations_translations_rels
  relations_translations: typeof relations_translations
  relations_site_settings: typeof relations_site_settings
  relations_redirects_rels: typeof relations_redirects_rels
  relations_redirects: typeof relations_redirects
  relations_search_rels: typeof relations_search_rels
  relations_search: typeof relations_search
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
