version: "3.8"
services:
  payload:
    image: simplyenak/website-backend:staging
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.swarm.network=dokploy-network
        - traefik.http.routers.development-payload-qah34c-64-web.rule=Host(`cms.system.simplyenak.com`)
        - traefik.http.routers.development-payload-qah34c-64-web.entrypoints=web
        - traefik.http.services.development-payload-qah34c-64-web.loadbalancer.server.port=3000
        - traefik.http.routers.development-payload-qah34c-64-web.service=development-payload-qah34c-64-web
        - traefik.http.routers.development-payload-qah34c-64-web.middlewares=redirect-to-https@file
        - traefik.http.routers.development-payload-qah34c-64-websecure.rule=Host(`cms.system.simplyenak.com`)
        - traefik.http.routers.development-payload-qah34c-64-websecure.entrypoints=websecure
        - traefik.http.services.development-payload-qah34c-64-websecure.loadbalancer.server.port=3000
        - traefik.http.routers.development-payload-qah34c-64-websecure.service=development-payload-qah34c-64-websecure
        - traefik.http.routers.development-payload-qah34c-64-websecure.tls.certresolver=letsencrypt
        - traefik.enable=true
        - traefik.http.routers.payload-cms.rule=Host(`cms.system.simplyenak.com`)
        - traefik.http.routers.payload-cms.entrypoints=websecure
        - traefik.http.routers.payload-cms.tls.certresolver=letsencrypt
        - traefik.http.routers.payload-cms.tls.domains[0].main=cms.system.simplyenak.com
        - traefik.http.services.payload-cms.loadbalancer.server.port=3000
    volumes:
      - payload-app-data:/app
      - payload-media-data:/app/public/media
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - NODE_ENV=production
      - PAYLOAD_PUBLIC_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
    command: ["node", "server.js"]
    networks:
      - dokploy-network
      - default
    depends_on:
      - payload-postgres
  payload-postgres:
    image: postgres:16-alpine
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - payload-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U payload
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
volumes:
  payload-app-data: null
  payload-media-data: null
  payload-database-data: null
